project:
  type: website
  render:
    - lesson_demarche_stat.qmd

website:
  title: "Cours Démarche statistique"
  navbar:
    left:
      - href: lesson_demarche_stat.qmd
        text: "Accueil"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    embed-resources: true
    self-contained: true
    
execute:
  freeze: auto