{
  "hash": "3143d840483a71eb9bcc1152f5f18859",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Démarche statistique\"\nauthor: \"Rémi Mahmoud\"\ndate: today\ndate-format: \"[remi.mahmoud@institut-agro.fr] <br> [https://demarche-stat-lesson.netlify.app]\"\nformat:\n   revealjs:\n    transition: slide\n    theme: serif\n    slide-number: c/t\n    fontsize: 120%\n    toc: false\n    toc-depth: 1\n    page-layout: full\n    embed-resources: false\n    # css: styles.css\n    css: styles.css\neditor: source\nfilters:\n  - parse-latex\n  - collapse-callout\nexecute:\n  freeze: auto\n  error: true\n\ncollapse-callout:\n  tip: true\n  note: true\n  warning: false\n  caution: true\n  important: false  \n---\n\n# Introduction\n\n::::::: {style=\"font-size: 140%;\"}\n## Objectifs\n\n\n-   Aborder les problèmes courants en analyse de données\n-   Argumenter le choix de procédures d'analyses\n-   Mettre en oeuvre une démarche d'analyse de données avec ![](images/R_logo.svg.png){fig-align=\"center\" width=\"5%\"}\n-   Interpréter & restituer les résultats d'une analyse\n\n. . .\n\nOn attend:\n\n:::::: columns\n::: {.column width=\"33%\"}\n**Attention**\n\n{{< fa ear-listen size=2xl >}}\n:::\n\n::: {.column width=\"33%\"}\n**Réflexion**\n\n{{< fa brain size=2xl >}}\n:::\n\n::: {.column width=\"33%\"}\n**Participation**\n\n{{< fa question size=2xl >}}\n:::\n::::::\n\n. . .\n\n**Evaluation:**\n\n2 CC (50%) + 1 projet (50%)\n:::::::\n\n## Quelques définitions (Wiki)\n\n-   ***LA*** **statistique**: discipline qui étudie les phénomènes à travers la collecte de **données**, leur traitement, leur analyse, l'interprétation et la présentation des résultats \\[...\\]. **Domaine des mathématiques + boîte à outils**. Fait partie de la **science des données**\n\n-   ***LES*** **statistiques**: type d'information obtenu en soumettant les valeurs à des opérations mathématiques.\n\n-   **L'analyse des données**: Famille de méthodes statistiques dont les principales caractéristiques sont d'être multidimensionnelles et descriptives.\n\n{{< fa triangle-exclamation >}}: en anglais, *data analysis* $\\Leftrightarrow$ Statistique\n\n. . .\n\n**En résumé**\n\nLa statistique s'intéresse à des jeux de données de taille raisonnable, fréquents dans vos domaines.\n\n## Les statistiques sont (utilisées) partout\n\n:::: r-stack\n::: {layout-nrow=\"3\"}\n![](images/co2_rich.PNG){.fragment width=\"80%\"}\n\n![](images/covid_groupe_sanguin.PNG){.fragment width=\"80%\"}\n\n![](images/figaro.PNG){.fragment width=\"80%\"}\n:::\n::::\n\n. . .\n\n-   En cela elles sont un outil *politique*, traduisant une certaine vision du monde et à manipuler avec précaution.\n\n## Coeur de la statistique\n\n-   Avoir les *bonnes* données:\n    -   observations d'un phénomène\n    -   sont-elles représentatives ?\n\n. . .\n\nEx. où renforcer l'avion ?\n\n:::: r-stack\n::: {layout-ncol=\"2\"}\n![](images/Survivorship-bias.svg){.fragment width=\"250\" height=\"200\"}\n\n![](images/bezos.PNG){.fragment width=\"450\" height=\"200\"}\n:::\n::::\n\n. . .\n\n-   Les résumer, les visualiser\n\n-   Se poser des questions:\n\n    -   Ex. pollution aux algues vertes: quelle variable utiliser ? Surface ? Masse ? Où/Quand/Comment faire des recueils ?\n    -   Cause / Conséquence (variété de blé / Rendement ; utilisation de phyto / diversité entomologique ; complexité du paysage)\n    -   Variables **explicatives** vs variable(s) **réponse(s)**\n\n------------------------------------------------------------------------\n\n-   Tous les effets ont-ils été pris en compte ?\n\n. . .\n\nEx. **paradoxe de Simpson** ([Vidéo complète sur le sujet](https://www.youtube.com/watch?v=vs_Zzf_vL2I&ab_channel=ScienceEtonnante){style=\"color:blue;\"} de Science Etonnante)\n\n\n::: {.cell}\n\n:::\n\n\n:::: r-stack\n::: {layout-ncol=\"2\"}\n![](images/death_rate_all.png){.fragment width=\"100%\"}\n\n![](images/death_rate_by_age.png){.fragment width=\"100%\"}\n:::\n::::\n\n. . .\n\n![](images/size_sample.png){width=\"40%\" fig-align=\"center\"}\n\n## Outil: R (moteur) / Rstudio (carrosserie) {.scrollable}\n\n-   Gratuit/libre/multi-plateforme\n-   Nombreux (+++) domaines d'applications (ex. ce cours a été réalisé sous R)\n-   BEAUCOUP d'aide dispo\n\n. . .\n\n**Installation:**\n\n::::: {layout-ncol=\"2\"}\n::: fragment\n1.  Télécharger et installer le **moteur** ![](images/R_logo.svg.png){width=\"10%\"} $\\rightarrow$ <https://cran.r-project.org/>\n:::\n\n::: fragment\n2.  Télécharger et installer la **carrosserie** ![](images/rstudio_logo.png){width=\"20%\"}\n:::\n:::::\n\n. . .\n\nOn peut aussi dessiner avec R (mais c'est une autre histoire)\n\n::: {#fig-casa layout-ncol=\"2\"}\n![Ridge](images/casa_1.png){#fig-ridge height=\"150\"}\n\n![Collatz](images/casa_2.png){#fig-collatz height=\"150\"}\n\n[Pierre Casadebaig](https://art.casadebaig.net/)\n:::\n\n## Quelques définitions (1/2)\n\n-   **Population**: ensemble d’entités objet de l’investigation statistique\n\n-   **Individu**: élément de la population d’étude\n\n-   **Echantillon**: ensemble des individus pour lesquels des valeurs ont été observées pour les variables de l’étude\n\n-   **Variable**: descripteur ou caractère des individus de la population d’étude\n\n-   **Inférence**: décider pour une population à partir des données observées de l’échantillon\n\n\n::: {.cell}\n\n:::\n\n\n::: r-stack\n![](images/plot_population.png){.fragment}\n\n![](images/plot_population_and_sample.png){.fragment}\n\n![](images/plot_population_and_sample_inference.png){.fragment}\n:::\n\n## Quelques définitions (2/2)\n\n::: {style=\"font-size: 140%;\"}\n**Nature des variables**:\n\n-   Qualitatives : les valeurs prises sont des *modalités*\n    -   nominale : pas de structure d'ordre {{< fa flag size=1xl >}}\n    -   ordinale : modalités ordonnées {{< fa ranking-star size=1xl >}}\n:::\n\n. . .\n\n::: {style=\"font-size: 140%;\"}\n-   quantitative: les valeurs prises sont *numériques*\n    -   discrete {{< fa arrow-up-9-1 size=1.5xl >}} {{< fa child size=1xl >}} {{< fa fish size=1xl >}}\n    -   continue {{< fa weight-scale size=1xl >}} *\\$*\n:::\n\n## Décrire les données à l'aide d'indicateurs\n\n::: {style=\"font-size: 85%;\"}\nSoit $x_1, x_2, ..., x_n$ une série de $n$ valeurs d'une variable X. On peut les décrire en utilisant des indicateurs de [position]{style=\"color:blue;\"} et de [dispersion]{style=\"color:red;\"} (que vous connaissez probablement)\n\n-   [moyenne:]{style=\"color:blue;\"} $\\color{blue}{\\bar{x} = \\frac{1}{n} \\sum x_i = \\frac{x_1 + x_2 + ... + x_n}{n}}$\n-   [médiane:]{style=\"color:blue;\"} $\\color{blue}{q_{0.5}(x) = }$ valeur telle que 50% des $x_i$ ont une valeur inférieure et 50% une valeur supérieure\n-   [1er quartile:]{style=\"color:blue;\"} $\\color{blue}{q_{0.25}(x) = }$ valeur telle que 25% des $x_i$ ont une valeur inférieure et 75% une valeur supérieure\n-   [3ème quartile:]{style=\"color:blue;\"} $\\color{blue}{q_{0.75}(x) = }$ valeur telle que 75% des $x_i$ ont une valeur inférieure et 25% une valeur supérieure\n-   [quantile $\\alpha$:]{style=\"color:blue;\"} $\\color{blue}{q_\\alpha(x) = }$ valeur telle que $100 \\times \\alpha$ % des $x_i$ ont une valeur inférieure et $100 - 100 \\times \\alpha$% une valeur supérieure\n-   [variance:]{style=\"color:red;\"} $\\color{red}{s^2(x) = \\hat{\\sigma}^2(x) = \\frac{1}{n-1}  \\sum (x_i - \\bar{x})^2}$\n-   [écart-type:]{style=\"color:red;\"} $\\color{red}{s(x) = \\sqrt{s^2(x)}}$\n:::\n\n\n::: {.cell}\n\n:::\n\n\n![](images/plot_descriptors.png){fig-align=\"center\"}\n\n## Un jeu de données comme fil conducteur\n\nL’association Air Breizh surveille la qualité de l’air et mesure la concentration de polluants comme l’ozone (O3, en $\\mu g.m^{-3}$) ainsi que les conditions météorologiques comme la température, la nébulosité, le vent, etc. Durant l’été 2001, 112 données ont été relevées à Rennes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nozone <- read.table(\"https://r-stat-sc-donnees.github.io/ozone.txt\",header=TRUE, stringsAsFactors = TRUE)\n\nhead(ozone)\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n maxO3 T9   T12  T15  Ne9 Ne12 Ne15 Vx9     Vx12    Vx15    maxO3v vent  pluie\n  87   15.6 18.5 18.4 4   4    8     0.6946 -1.7101 -0.6946  84    Nord  Sec  \n  82   17.0 18.4 17.7 5   5    7    -4.3301 -4.0000 -3.0000  87    Nord  Sec  \n  92   15.3 17.6 19.5 2   5    4     2.9544  1.8794  0.5209  82    Est   Sec  \n 114   16.2 19.7 22.5 1   1    0     0.9848  0.3473 -0.1736  92    Nord  Sec  \n  94   17.4 20.5 20.4 8   8    7    -0.5000 -2.9544 -4.3301 114    Ouest Sec  \n  80   17.7 19.8 18.3 6   6    7    -5.6382 -5.0000 -6.0000  94    Ouest Pluie\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Une question:**\n\n-   Peut-on prévoir la concentration en ozone du lendemain pour avertir la population en cas de pic de pollution ?\n\n# Visualisation\n\n## La visualisation: pourquoi ?\n\n-   Quels points communs entre ces 4 jeux de données ?\n\n::: r-stack\n![](images/anscombe_quartet.png){.fragment width=\"700\" height=\"450\"}\n\n![](images/anscombe_quartet_answer.png){.fragment width=\"700\" height=\"450\"}\n:::\n\n## Visualisation: quels choix ?\n\n-   La visualisation dépend de:\n    -   La nature des données (nature des variables, nb d'individus)\n\n    -   La problématique: qu'est-ce que je veux montrer ?\n\n    -   [le site data-to-viz.com](https://www.data-to-viz.com/){style=\"color:blue;\"} permet de trouver de bonnes idées\n\n. . .\n\n-   La visualisation permet de:\n    -   comprendre / explorer / vérifier les données\n    -   suggérer des analyses\n    -   *faire passer des idées*\n\n. . .\n\n**Les graphiques sont ce qu'on retient de nombreux rapports / analyses / articles scientifiques.**\n\n. . .\n\nSur ![](images/R_logo.svg.png){fig-align=\"center\" width=\"5%\"}, le package `ggplot2` permet de faire des visualisations allant du plus simple au plus compliqué.\n\n## GGplot - Quick tuto\n\n. . .\n\n![](images/building_blocks_ggplot.png)\n\n## GGplot - Exemple: distribution d'une variable quantitative\n\n<!-- code-line-numbers=\"|6|9\" -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(ozone) # création de l'objet ggplot\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## GGplot - Exemple: distribution d'une variable quantitative {transition=\"none\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ozone, aes(x = maxO3)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en x\n  geom_histogram() # ajout d'une couche HISTOGRAMME \n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n## GGplot - Exemple: distribution d'une variable quantitative {transition=\"none\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nggplot(ozone, aes(x = maxO3)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en x\n  geom_histogram() + # ajout d'une couche HISTOGRAMME +\n  labs(title = \"un joli titre\", x=  \"un joli titre pour l'axe x\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n## GGplot - Exemple: distribution d'une variable quantitative {transition=\"none\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ozone, aes(x = maxO3)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en x\n  geom_histogram(bins =20) + # ajout d'une couche HISTOGRAMME, classes plus grossières\n  labs(title = \"un joli titre\", x=  \"un joli titre pour l'axe x\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## GGplot - Exemple: distribution d'une variable quantitative {transition=\"none\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2\"}\nggplot(ozone, aes(y = maxO3)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en y\n  geom_boxplot() + # ajout d'une couche boxplot\n  labs(title = \"Boxplot du maximum d'ozone\", x=  \"un joli titre pour l'axe x\", y = \"Maximum d'ozone\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n## GGplot - Exemple: distribution d'une variable quantitative {transition=\"none\"}\n\nMoche ? Pensez à `theme_bw()` (black & white)\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nggplot(ozone, aes(y = maxO3)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en y\n  geom_boxplot() + # ajout d'une couche boxplot, classes plus grossières\n  labs(title = \"Boxplot du maximum d'ozone\", y = \"Maximum d'ozone\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n## Distribution d'une variable qualitative (1/2) {.scrollable}\n\n::: {style=\"font-size: 100%;\"}\nLe camembert c'est bon, mais *seulement en fromage*. SINON CA PUE TROP.\n:::\n\n. . .\n\n::: {style=\"font-size: 100%;\"}\nQuelle classe est la plus représentée ?\n:::\n\n![](images/pie_bad_idea.png){width=\"100%\" fig-align=\"center\" height=\"240\"}\n\n![](images/barplot_good_idea.png){.fragment width=\"100%\" fig-align=\"center\" height=\"240\"}\n\n## Distribution d'une variable qualitative (2/2) {.scrollable}\n\n*Alternative: graphiques en barre*\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(ozone, aes(x = vent)) + # création de l'objet ggplot, en spécifiant ce qu'on veut en x\n  geom_bar() + # ajout d'une couche barplot\n  theme_bw() + \n  labs(y = \"Nb de jours\", title = \"Nombre de jours par direction de vent\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=336}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(dplyr)\n\nozone %>% \n  summarise(prop_vent = n()/nrow(ozone), .by = vent) %>% # On résume le jeu de donnée par direction de vent, on calcule le nb de chaque catégorie sur la longueur totale du jeu de données\n  mutate(vent = reorder(vent, prop_vent)) %>% # trier le facteur pour ordonner les catégories \n  ggplot(aes(x = vent, y= prop_vent)) +\n  labs(y = \"%\") +\n  geom_col(alpha = .5)+ # 50% de transparence\n  scale_y_continuous(labels=scales::percent) +\ngeom_text(aes(label=scales::percent(prop_vent)), vjust = -1.5)+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=336}\n:::\n:::\n\n\n## Effet d'une / deux variable(s) sur une variable quanti\n\n<!-- #| class-source: my_class2 -->\n\n<!-- #| classes: my_class2 -->\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggplot(ozone, aes(x = T9, y= maxO3)) + \n  geom_point() + # ajout points\n  geom_smooth(method = \"lm\", se = FALSE) + # Ajout ajustement linéaire\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-14-1.png){width=480}\n:::\n:::\n\n\n<!-- #| class-source: my_class2 -->\n\n<!-- #| classes: my_class2 -->\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggplot(ozone, aes(x = T9, y= maxO3, color = vent)) + # ajout d'une couleur\n  #par direction du vent\n  geom_point() + # ajout points\n  geom_smooth(method = \"lm\", se = FALSE) + # Ajout ajustement linéaire\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-15-1.png){width=480}\n:::\n:::\n\n\n## Effet d'une / deux variable(s) quali sur une variable quanti (1/2) {.scrollable}\n\n. . .\n\n<!-- #| class-source: my_class2 -->\n\n<!-- #| classes: my_class2 -->\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggplot(ozone, aes(x = vent,\n                  y= maxO3,\n                  fill=vent,\n                  col=vent)) + # dans aes: ce qui DEPEND du jeu de données\n  geom_boxplot(outlier.shape=NA,alpha=0.4) + # alpha : transparence\n  geom_point(position = position_jitter(width = 0.05, height= 0)) + # ajout \n  # points, avec perturbation horizontale pour faciliter visu\n  theme_bw() +\n  labs(title =\"Effet du vent sur le max d'ozone\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-16-1.png){width=480}\n:::\n:::\n\n\n## Effet de deux variable(s) quali sur une variable quanti (2/2)\n\n::: {style=\"font-size: 100%;\"}\nQuid d'une interaction potentielle vent pluie ?\n:::\n\n. . .\n\n::: {style=\"font-size: 100%;\"}\n*Point code* : La fonction `%>%` de `dplyr` permet de passer des arguments en chaîne dans des fonctions. Par ex.:\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\nx <- 1:3\nmax(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .my_class_code_big .cell-code}\nlibrary(dplyr) # permet d'utiliser %>% \nx %>% max # equivaut à max(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n:::\n\n. . .\n\n\n::: {.cell .my_class_code_big output-location='column-fragment'}\n\n```{.r .my_class_code_big .cell-code  code-fold=\"true\"}\nlibrary(dplyr)\nozone %>% \n  summarise(moy_O3 = mean(maxO3), .by =  c(vent, pluie)) %>% \n  # MOYENNER LES VALEURS DE MAXO3 PAR VENT ET PLUIE \n  #ET PASSER LE RESULTAT DANS GGPLOT VIA %>% \n  ggplot(aes(x = vent, y= moy_O3, group = pluie, color =pluie)) +\n  geom_line() +\n  geom_point() +\n  theme_bw() +\n  labs(title =\"Interaction pluie:vent sur le max03\",\n       y = \"Moyenne de maxO3\", x = \"Direction du vent\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## Des visualisations vers les tests statistiques\n\nLes visus précédentes nous ont permis d'intuiter certaines tendances.\n\n::::: columns\n::: {.column width=\"50%\"}\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-19-1.png){width=384}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-20-1.png){width=384}\n:::\n:::\n\n:::\n:::::\n\n. . .\n\nPeut-on les généraliser ? Rappel:\n\n![](images/plot_population_and_sample_inference.png){.fragment width=\"60%\" height=\"280\" fig-align=\"center\"}\n\n. . .\n\nC'est toute la question des *tests statistiques*.\n\n# Principes et applications des tests statistiques\n\n## De la question aux tests\n\n-   On dispose de multiples variables, toutes présentant potentiellement un intérêt\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\ncolnames(ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"maxO3\"  \"T9\"     \"T12\"    \"T15\"    \"Ne9\"    \"Ne12\"   \"Ne15\"   \"Vx9\"   \n [9] \"Vx12\"   \"Vx15\"   \"maxO3v\" \"vent\"   \"pluie\" \n```\n\n\n:::\n:::\n\n<!-- #| classes: my_class_code -->\n<!-- #| class-source: my_class_code -->\n. . .\n\n-   Ici une variable particulière nous intéresse (c'est un *choix* ; guidé par la littérature scientifique / les politiques publiques etc. ): maxO3 (car étant clé pour la pollution de l'air). C'est la **variable réponse**\n\n. . .\n\nOn peut se poser plusieurs questions:\n\n-   Effet du vent sur le max d'ozone ?\n-   Le temps sec/pluvieux influence-t-il le max d'ozone ? De la même manière selon les différentes directions du vent ?\n\n**Objectif** : [Généraliser (inférer) au-delà des données de l'échantillon]{style=\"color:blue;\"}\n\n**Problème** : [Comment gérer l'incertitude liée au fait qu'on a observé qu'une petite partie des données]{style=\"color:red;\"}\n\n. . .\n\n*Faisons d'abord un détour par la notion de distribution statistique et de loi de probabilité*\n\n## Rappel sur la notion de distribution statistique / loi de probabilité\n\n-   **Définition :**\\\n    Une distribution statistique décrit comment les valeurs d'une variable se répartissent dans un ensemble de données.\n\n-   **Types de variables :**\n\n    -   *Quantitatives* : mesurables (ex : taille des plantes).\n    -   *Qualitatives* : catégories (ex : variétés de cultures).\n\n. . .\n\n\n*En théorie, une distribution peut s'approcher d'une loi de probabilité.*\n\n. . .\n\n\n::::: columns\n::: {.column width=\"30%\"}\n\n\nUn exemple classique de loi de probabilité que vous connaissez probablement : la loi normale.\n\n:::\n\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n\n:::::\n\n. . .\n\n__Interprétation probabiliste__\n\n-   La probabilité qu’une variable aléatoire appartienne à un intervalle donné est proportionnelle à la surface sous la courbe de distribution pour cet intervalle.\n\n<!-- . . . -->\n\n<!-- En termes mathématiques: -->\n\n<!-- $X$ variable aléatoire continue ayant pour densité $f$. -->\n\n<!-- On a $\\mathbb{P}(a \\leq X \\leq b) = \\int_a^b f(t)dt$. -->\n\n\n## Décrire une loi de probabilité\n\nIl existe de beaucoup de lois de probabilités, qu'on peut décrire via différents paramètres.\n\n. . .\n\n**Quelques paramètres descriptifs d'une loi**\n\n::::: columns\n\n::: {.column width=\"50%\"}\n\n-   **Tendance centrale :**\n    -   Moyenne : la \"valeur attendue\".\n    -   Médiane : la valeur au milieu de la distribution.\n    -   Mode : la valeur la plus fréquente.\n-   **Dispersion :**\n    -   Variance / écart-type\n    -   IQR / étendue\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: .fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-23-1.png){width=768}\n:::\n:::\n\n:::\n\n:::\n:::::\n\n\n. . .\n\n\n**Loi normale et règle des 68-95-99**\n\n-   **Loi normale** : Distribution en forme de cloche centrée autour de la moyenne.\n-   **Règle 68-95-99** :\n    -   68% des données se trouvent à ±1 écart-type ($\\sigma$) de la moyenne.\n    -   95% à ±2 écarts-types.\n    -   99.7% à ±3 écarts-types.\n\n------------------------------------------------------------------------\n\n**Illustration de la règle 68-95-99**\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n## Rappel: Théorème central limite\n\n. . .\n\nLa moyenne $\\bar X$ de $n$ valeurs issues d'une variable $X$ de loi quelconque, de moyenne $\\mu$ et de variance $\\sigma^2$, suit la loi (si $n > 30$ ou $X \\sim \\mathcal{N}$)\n\n$$\\bar X \\sim {\\cal N} (\\mu, \\sigma^2/n) \\quad   \\mbox{et donc} \\quad \\frac{\\bar X - \\mu}{\\sqrt{\\sigma^2/n}} \\sim {\\cal N} (0, 1)$$\n\n. . .\n\n::: {style=\"font-size: 85%;\"}\n-   En pratique, $\\sigma^2$ rarement connu, et donc doit être estimé à partir de l'échantillon\n:::\n\n. . .\n\n::: {style=\"font-size: 85%;\"}\n-   $\\Longrightarrow$ augmente un peu l'incertitude $\\Longrightarrow$ utilisation d'une loi de Student $(n-1)$ degrés de liberté (plutôt qu'une loi normale) : $\\frac{\\bar X - \\mu}{\\sqrt{S^2/n}} \\sim \\mathcal{T}(n-1)$\n:::\n\n. . .\n\n::: {style=\"font-size: 85%;\"}\nD'où l'intervalle de confiance de $\\mu$ au niveau de confiance 95%:\n\n$\\left[~\\bar x - \\frac{s}{\\sqrt{n}}t_{1-\\alpha/2}(n-1)~;~ \\bar x + \\frac{s}{\\sqrt{n}}t_{1-\\alpha/2}(n-1)~\\right]$\n\n\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\nt.test(ozone$maxO3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  ozone$maxO3\nt = 33.905, df = 111, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 85.02578 95.58136\nsample estimates:\nmean of x \n 90.30357 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\nx <- ozone$maxO3\n\nmean(x) - qt(0.975,df = 111)*sd(x)/sqrt(length(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 85.02578\n```\n\n\n:::\n\n```{.r .my_class_code_big .cell-code}\nmean(x) + qt(0.975,df = 111)*sd(x)/sqrt(length(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 95.58136\n```\n\n\n:::\n:::\n\n\n:::\n\n:::::\n\n:::\n\n## Intervalle de confiance vers test de conformité\n\n-   On suppose / connaît $\\frac{\\bar X - \\mu}{\\sqrt{S^2/n}} \\sim {\\mathcal T}(n-1)$.\n\n. . .\n\n-   On peut maintenant tester si la moyenne est égale à une valeur particulière, par ex est-ce que $\\mu = 100$ ?\n\n. . .\n\nA partir d'un échantillon $x$, on peut calculer $\\bar{x}$ et $s^2$ et se demander si la valeur est typique d'une loi de Student à n-1 ddl.\n\n. . .\n\n**Quelques définitions**\n\n-   $H_0$ hypothèse nulle, $H_0: \\mu = 100$ vs $H_1$ hypothèse alternative, $H_1: \\mu \\neq 100$\n\n. . .\n\n-   **Statistique de test**: $\\frac{\\bar X - \\mu}{\\sqrt{S^2/n}}$: il s'agit de la valeur qu'on peut calculer à partir de l'échantillon, et qu'on suppose suivre une certaine loi **sous** $H_0$: ici une loi de Student à $n-1$ ddl\n\n. . .\n\n-   **p-value** du test: probabilité calculée sous $H_0$, que la statistique de test soit plus extrême que la valeur observée Tobs\n\n> p-value: \"Dans un monde où $H_0$ est vraie, la probabilité d'obtenir une valeur au moins aussi extrême pour la statistique de test est de p\"\n\nSi p \\< 0.05, on rejette l'hypothèse $H_0$ au seuil de 5%\n\n------------------------------------------------------------------------\n\n\n::::: columns\n::: {.column width=\"30%\"}\n\nDans notre cas, n = 112, donc $T$ est censée suivre une loi de Student à 111 ddl, sous $H_0$:\n\n:::\n<!-- . . . -->\n\n::: {.column width=\"70%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::::\n\n::: {.cell}\n\n:::\n\n\n. . .\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\nt.test(ozone$maxO3, mu = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  ozone$maxO3\nt = -3.6406, df = 111, p-value = 0.0004148\nalternative hypothesis: true mean is not equal to 100\n95 percent confidence interval:\n 85.02578 95.58136\nsample estimates:\nmean of x \n 90.30357 \n```\n\n\n:::\n\n```{.r .my_class_code_big .cell-code}\n# MEME CHOSE\nTobs <- sqrt(112)*(mean(ozone$maxO3 )- 100)/(sd(ozone$maxO3))\n2*pt(Tobs, 111)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0004147533\n```\n\n\n:::\n:::\n\n:::\n\n<!-- . . . -->\n\n::: {.column width=\"50%\"}\nPour une loi de Student à n-1 ddl, -3.64 est une valeur *peu probable* donc on rejette $H_0$, au seuil de 5%.\n:::\n:::::\n\n<!-- . . . -->\n\n<!-- Ici, on a testé $H_0$ vs H1 : $\\mu \\neq 100$ (alternative = \"two.sided\") mais on aurait pu testeer H1: $\\mu < 100$ (alternative = \"less\") ou H1: $\\mu > 100$ (alternative = \"greater\") -->\n\n## Comparaison de 2 moyennes (1/2)\n\n**Question**: le temps (sec/pluvieux) a-t-il un effet sur le max d'ozone ?\n\n. . .\n\nRéflexe: visu !\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>% \n  ggplot(aes(x = pluie, y = maxO3, fill = pluie, col = pluie)) +\n  geom_point(position = position_jitter(width = .05, height = 0)) +\n  geom_boxplot(alpha=  .3, outlier.shape = NA) + \n  theme_bw() + theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-30-1.png){width=480}\n:::\n:::\n\n\n. . .\n\nPasser de l'échantillon à n'importe quel jour induit de l'incertitude. Mais, il est plus facile de conclure qu'il y a une différence entre les deux moyennes *dans la population* si:\n\n1.  Les moyennes sont très différentes ({{< fa smoking size=1xl >}} vs {{< fa ban-smoking size=1xl >}})\n2.  La variabilité du maximum d'ozone est faible au sein des jours pluvieux et au sein des jours secs\n3.  Il y a beaucoup de données\n\n## Comparaison de 2 moyennes (2/2)\n\nOn considère que les données de la sous-population 1 sont telles que $(X_{i1})_{1\\leq i\\leq n_1} \\sim {\\cal N}(\\mu_1,\\sigma^2)$ et que les données de la sous-population 2 sont telles que $(X_{i2})_{1\\leq i\\leq n_2} \\sim {\\cal N}(\\mu_2,\\sigma^2)$ $\\Rightarrow$ (pour l'instant) seules les moyennes peuvent être différentes\n\n. . .\n\n-   **$H_0$ hypothèse nulle**, $H_0: \\mu_1 = \\mu_2$ vs **$H_1$ hypothèse alternative**, $H_1: \\mu_1 \\neq\\mu_2$\n\n. . .\n\n-   **Statistique de test**: $T = \\frac{\\bar{X_1} - \\bar{X_2}}{\\sqrt{\\frac{\\hat{\\sigma}^2}{n_1} + \\frac{\\hat{\\sigma}^2}{n_2}}}$\n\n. . .\n\n-   Sous $H_0$, T suit une loi de Student $n_1 + n_2 -2$\n\n. . .\n\n> Si les variances sont inégales, le test est différent $\\Longrightarrow$ tester l'égalité des variances avant de faire le test de comparaison de moyennes\n\n## Test de comparaison de 2 variances\n\n::::::: columns\n::::: {.column width=\"50%\"}\n-   $H_0$ hypothèse nulle, $H_0:\\sigma_1^2=\\sigma_2^2$ vs $H_1$ hypothèse alternative, $H1: \\sigma_1^2\\ne\\sigma_2^2$\n\n$\\Longleftrightarrow~~H_0:\\frac{\\sigma_1^2}{\\sigma_2^2}=1$ contre $H_1:\\frac{\\sigma_1^2}{\\sigma_2^2}\\ne 1$\n\n::: fragment\n-   Statistique de test: $F=\\frac{S_1^2}{S_2^2}$\n:::\n\n::: fragment\n-   Sous $H_0$, F suit une loi de Fisher à $n_1 - 1$ et $n_2 - 1$ ddl\n:::\n:::::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n:::\n:::::::\n\n## Mise en pratique\n\n:::: columns\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\nvar.test(maxO3 ~ pluie, data = ozone, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  maxO3 by pluie\nF = 0.35906, num df = 42, denom df = 68, p-value = 0.0005659\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.2108847 0.6338374\nsample estimates:\nratio of variances \n         0.3590605 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"30%\"}\n\n::: .fragment\n\n> Ici on rejette $H_0$ au seuil de 5%, les variances sont différentes\n\n:::\n\n:::\n\n::::\n\n. . .\n\n\n::: {.cell .my_class_code_big}\n\n```{.r .my_class_code_big .cell-code}\n# NOTEZ LE VAR.EQUAL\nt.test(maxO3 ~pluie, data = ozone, alternative = \"two.sided\", var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  maxO3 by pluie\nt = -6.3362, df = 109.88, p-value = 5.321e-09\nalternative hypothesis: true difference in means between group Pluie and group Sec is not equal to 0\n95 percent confidence interval:\n -36.02936 -18.86110\nsample estimates:\nmean in group Pluie   mean in group Sec \n           73.39535           100.84058 \n```\n\n\n:::\n:::\n\n\n> On rejette $H_0$, on affirme que les moyennes sont significativement différentes\n\n## Erreur et puissance d'un test\n\n. . .\n\nDécision d'un test prise pour la population (\"il y a plus d'ozone les jours sec\") alors qu'on n'observe qu'un échantillon\n\n$\\Rightarrow$ Décision incertaine, et deux erreur possibles\n\n-   **Erreur de première espèce**: rejeter $H_0$ alors que celle-ci est vraie: faux positif\n-   **Erreur de deuxième espèce** : ne pas rejeter $H_0$ alors que celle-ci est fausse: faux négatif\n\nEn image ({{< fa question size=1xl >}} **qu'est-ce que H0 ici ?**):\n\n. . .\n\n![](images/type_1_2_error.png){width=\"80%\" fig-align=\"center\" height=\"250\"}\n\n. . .\n\n> un test est dit puissant si son erreur de 2ème espèce est petite. La **puissance d'un test** est la probabilité de rejeter $H_0$ et d'avoir raison\n\n## Puissance d'un test (1/2)\n\n**Question souvent posée** Combien de données faut-il pour tester une différence entre 2 moyennes ?\n\nPar ex.: combien de patients pour tester s'il y a une diff entre 2 médicaments pour faire baisser le taux de cholestérol ?\n\n. . .\n\nRappel: de quoi est-ce que ça dépend ?\n\n-   {{< fa question size=1xl >}}\n-   {{< fa question size=1xl >}}\n-   {{< fa question size=1xl >}}\n\n. . .\n\n**Reformuler la question**\n\nCombien faut-il de patients pour mettre en évidence une différence d'au moins 0.2g/l entre les 2 médicaments ?\n\n. . .\n\nToujours pas possible {{< fa face-frown size=1xl >}}\n\n. . .\n\nMAAAAAIS {{< fa face-smile size=1xl >}}\n\n## Puissance d'un test (2/2)\n\n**MAAAAAIS** {{< fa face-smile size=1xl >}} si;\n\n-   on connaît la variance de la variable d'intérêt (ex. expériences antérieures montrent un écart-type de 0.4g/l) (`sd`)\n-   on veut détecter une différence donnée par ex toute diff \\> 0.2g/l (`delta`)\n-   on veut détecter cette différence avec proba de 80% (`power`)\n\n**alors c'est possible** {{< fa face-smile-wink size=1xl >}}\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\npower.t.test(delta=  0.2, \n             sd = 0.4, power = .80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76576\n          delta = 0.2\n             sd = 0.4\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n# Analyse de variance à un facteur\n\n## Test de l'effet d'un facteur\n\n::::: columns\n::: {.column width=\"60%\"}\nPar ex. *la direction du vent a-t-elle un effet sur le maximum d'ozone* ?\n\n**Variable réponse quantitative**, notée Y: maxO3\n\n**Variable explicative qualitative à I modalités (groupes)**: direction du vent\n\nC'est le cadre de l'ANOVA (**AN**alysis **O**f **VA**riance)\n:::\n\n::: {.column width=\"40%\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n maxO3  vent\n    87  Nord\n    82  Nord\n    92   Est\n   114  Nord\n    94 Ouest\n    80 Ouest\n```\n\n\n:::\n:::\n\n:::\n:::::\n\nRéflexe ... {{< fa question size=1xl >}} {{< fa question size=1xl >}} {{< fa question size=1xl >}}\n\n. . .\n\nVisu!\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>% \n  ggplot(aes(x = vent, y = maxO3, fill = vent, col = vent)) +\n  geom_point(position = position_jitter(width = .05, height = 0)) +\n  geom_boxplot(alpha=  .3, outlier.shape = NA) + \n  theme_bw() + \n  labs(title = \"Effet du vent sur le max d'ozone\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-36-1.png){width=528}\n:::\n:::\n\n\n. . .\n\n**Question de base modifiée en : la moyenne du maximum d'ozone est-elle la même pour chaque direction du vent ?**\n\n## Problématique qui revient souvent\n\n-   L'effet de cultures intermédiaires est-il le même selon l'espèce/variété ?\n\n. . .\n\n-   La présence de haies a-t-elle une influence sur la population d'auxiliaires de cultures ?\n\n. . .\n\n-   Y a-t-il un effet de la variété sur le rendement du blé dans telle expérimentation ?\n\n-   etc. etc. etc.\n\n. . .\n\nDe manière générale, l'ANOVA est le cadre d'analyse de **l'effet d'une variable qualitative** à *I* modalités (par ex. sol nu / moutarde / phacélie) sur une **variable quantitative**\n\n. . .\n\nMais alors pourquoi parler d'Analyse de Variance si on veut comparer des moyennes ?\n\n. . .\n\nLa réponse viendra avec les explications (et les mains dans le cambouis)\n\n## Mettons les mains dans le cambouis\n\n**Données & notations**\n\n\\begin{center}\n\\footnotesize\n\\begin{tabular}{lcc}\n  % after \\\\: \\hline or \\cline{col1-col2} \\cline{col3-col4} ...\n\\hline\\hline\nvent&maxO3& Notation\\\\\n\\hline\nEst&92&$y_{11}$\\\\\nEst&121&$y_{12}$\\\\\nNord&87&$y_{21}$\\\\\nNord&82&$y_{22}$\\\\\nOuest&94&$y_{31}$\\\\\nOuest&80&$y_{32}$\\\\\nSud&90&$y_{41}$\\\\\n \\ldots&\\ldots&\\ldots\\\\\n\\hline\\hline\n\\end{tabular}\n\\normalsize\n\\end{center}\n\n$y_{ij}$ valeur de $Y$ pour l'individu $j$ du groupe $i$\n\n. . .\n\nMoyenne du groupe $i$: $y_{i\\bullet}=\\frac{1}{n_i}\\sum_{j=1}^{n_i} y_{ij}$\n\nMoyenne générale : $y_{\\bullet\\bullet}=\\frac{1}{n}\\sum_{i=1}^I\\sum_{j=1}^{n_i} y_{ij}$\n\n## Comparaison de I moyennes\n\n-   Dans chaque groupe, on considère que les données suivent une loi $\\mathcal{N}(\\mu_i, \\sigma^2)$\n\nOn considère le **MEME** $\\sigma^2$.\n\n. . .\n\n\\begin{center}\n$Y_{1j} \\sim {\\cal N}(\\mu_1,\\sigma^2)$ peut s'érire $Y_{1j} = \\mu_1 + \\varepsilon_{1j}\\mbox{ avec }\\varepsilon_{1j}\\sim {\\cal N}(0,\\sigma^2)$\\\\\n$Y_{2j} \\sim {\\cal N}(\\mu_2,\\sigma^2)$ peut s'écrire $Y_{2j} = \\mu_2 + \\varepsilon_{2j}\\mbox{ avec }\\varepsilon_{2j}\\sim {\\cal N}(0,\\sigma^2)$\\\\\n\\ldots ~~~~~~~~~~~~~~~~~~~~~~~~~~\\ldots\\\\\n$Y_{Ij} \\sim {\\cal N}(\\mu_I,\\sigma^2)$ peut s'écrire $Y_{Ij} = \\mu_I + \\varepsilon_{Ij}\\mbox{ avec }\\varepsilon_{Ij}\\sim {\\cal N}(0,\\sigma^2)$\n\\end{center}\n\n$\\Rightarrow$ On peut résumer tout ça dans un seul modèle:\n\n. . .\n\n$$ \\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\mu_i+ \\varepsilon_{ij}\\\\\n\\forall i,j~~~~{\\cal L}(\\varepsilon_{ij})={\\cal N}(0,\\sigma^2)\\\\\n\\forall (i,j)\\neq (i',j')~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right. $$\n\n## Deux définitions du modèle\n\nSi $Y_{ij}$ est la valeur de la réponse du j$^{eme}$ individu ($j = 1, . . . , n_i$) du i$^{eme}$ groupe ($i = 1, . . . , I$):\n\n::::: columns\n::: {.column width=\"50%\"}\n![](images/modele_aov_mu.png){width=\"100%\" fig-align=\"center\" height=\"250\"}\n\n$$ \\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\mu_i+ \\varepsilon_{ij}\\\\\n\\forall i,j~~~~{\\cal L}(\\varepsilon_{ij})={\\cal N}(0,\\sigma^2)\\\\\n\\forall (i,j)\\neq (i',j')~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right. $$\n\n$I$ paramètres: les $\\mu_i$\n:::\n\n::: {.column width=\"50%\"}\n![](images/modele_aov_alpha.png){width=\"100%\" fig-align=\"center\" height=\"250\"}\n\n$$\\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\mu+\\alpha_i+ \\varepsilon_{ij}\\\\\n\\forall i,j~~~~{\\cal L}(\\varepsilon_{ij})={\\cal N}(0,\\sigma^2)\\\\\n\\forall (i,j)\\neq (i',j')~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right.$$\n\n$I + 1$ paramètres: l'effet moyen $\\mu$ et les $I$ coefficients $\\alpha_i$ (effet du niveau i)\n:::\n:::::\n\nOn doit avoir $\\forall~i,~~\\mu+\\alpha_i=\\mu_i$ \\Rightarrow besoin de **contraintes**\n\n## Estimer les paramètres du modèle\n\nOn minimise les écarts entre observations ($Y_{ij}$) et prédictions par le modèle $\\hat{Y}_{ij}$.\n\nOn minimise le **critère des moindres carrés ordinaires** ({{< fa question size=1xl >}}: pourquoi carré $^2$ ?)\n\n. . .\n\n$$   SCER  =  \\sum_{i=1}^{I}\\sum_{j=1}^{n_i}\\left( Y_{ij} - \\hat Y_{ij} \\right)^{2}=\\sum_{i=1}^{I}\\sum_{j=1}^{n_i} \\left( Y_{ij} - (\\hat\\mu +\\hat\\alpha_i) \\right)^{2} $$\n\n$$\\mbox{SCER minimal quand }\\forall~i,~\\hat\\mu +\\hat\\alpha_i=\\frac{1}{n_i}\\sum_{j=1}^{n_i}Y_{ij}=Y_{i\\bullet}$$\n\n. . .\n\n*Contraintes classiques*:\n\n-   Un niveau particulier comme référence: $\\alpha_1 = 0 \\ \\Rightarrow \\hat\\mu=Y_{1\\bullet}$ et $\\forall i, \\hat{\\alpha}_i=Y_{i\\bullet}-Y_{1\\bullet}$\n\n-   la moyenne des moyennes par groupe comme référence: $\\sum_{i=1}^I\\alpha_i=0 \\ \\Rightarrow \\hat\\mu=\\frac{1}{I}\\sum_{i=1}^I Y_{i\\bullet},  ~~ \\forall \\,i,\\,\\hat\\alpha_i=Y_{i\\bullet}-\\hat\\mu$\n\n## Exemple pour clarifier\n\n\\begin{center}\n\\begin{tabular}{|c|c|c|c|} \n\\hline\ngroupe 1&groupe 2&groupe3& \\\\\n\\hline\n$y_{11}=6$ & $y_{21}=2$ & $y_{31}=3$ &\\\\\n$y_{12}=9$ & $y_{22}=4$ & $y_{32}=1$ &\\\\\n$y_{13}=6$ & $y_{22}=3$ &   &\\\\\n\\hline \\\\\n\\hline\n$y_{1\\bullet}=7$ & $y_{2\\bullet}=3$ & $y_{3\\bullet}=2$ & $y_{\\bullet\\bullet}=4.25$\\\\\n\\hline\n\\end{tabular}\n\\end{center}\n\n. . .\n\n-   Avec traitement 1 comme référence : $\\hat\\mu= 7$; $\\hat\\alpha_1=0$; $\\hat\\alpha_2=-4$ et $\\hat\\alpha_3=-5$\n\n-   $\\sum_{i=1}^I \\alpha_i=0$ : $\\hat\\mu= \\frac{1}{3}(7+3+2)=4$ ; $\\hat\\alpha_1=3$ ; $\\hat\\alpha_2=-1$ et $\\hat\\alpha_3 = -2$\n\n. . .\n\n\n\n\n<!-- > [L'interprétation d'un coefficient $\\alpha_i$ dépend de la contrainte choisie !]{style=\"color:red;\"} -->\n\n\n<!-- . . . -->\n\n::: callout-important\n## Important\n\n[Le choix de la contrainte impacte FORTEMENT l'interprétation]{style=\"color:red;\"}\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\n1.  $\\sum_i \\alpha_i= 0$, la comparaison est faite par rapport à la moyenne des moyennes par modalité\n2.  $\\alpha_1= 0$, la comparaison est faite par rapport à un niveau de ref (*moins intuitif, et pas pratique quand présence d'interactions*)\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\n*Certaines fonctions de R par défaut utilisent la contrainte 2. !*\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\nComparez les sorties de ces différentes lignes de code...\n:::\n\n:::::: columns\n::: {.column .incremental width=\"20%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n#lm par défaut\ncoef( lm(maxO3 ~ pluie,\n         data= ozone) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    pluieSec \n   73.39535    27.44523 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column .incremental width=\"35%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n#lm en spécifiant le contraste\ncoef(lm(maxO3 ~ pluie,\n        data = ozone,\n        contrasts = list(pluie= \"contr.sum\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      pluie1 \n   87.11796   -13.72262 \n```\n\n\n:::\n:::\n\n:::\n\n\n::: {.column .incremental width=\"45%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n# LinearModel prémâche le travaille\nLinearModel(maxO3 ~ pluie,\n            data= ozone)$Ttest\n```\n:::\n\n\n\n::: {.cell .my_class_code}\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error t value Pr(>|t|)\n(Intercept)      87.12       2.42   36.01        0\npluie - Pluie   -13.72       2.42   -5.67        0\npluie - Sec      13.72       2.42    5.67        0\n```\n\n\n:::\n:::\n\n:::\n::::::\n\n\n## Variance résiduelle\n\n**Valeurs prédites**: $\\hat y_{ij} = \\hat{\\mu} + \\hat{\\alpha}_i = y_{i\\bullet}$\n\n. . .\n\n**Erreurs d'ajustement ou résidus** : $\\hat\\varepsilon_{ij}=y_{ij}-\\hat y_{ij}=y_{ij}-y_{i\\bullet}$\n\n. . .\n\n**Estimateur de la variabilité résiduelle** $\\sigma^2$:\n\n$$\\hat \\sigma^2=\\frac{\\sum_{ij}(Y_{ij}-Y_{i\\bullet})^2}{n-I}=\\frac{\\sum_{ij}\\hat\\varepsilon_{ij}^2}{n-I}~~~~~~~~~~\\mathbb{E}(\\hat\\sigma^2)=\\sigma^2$$\n\n$n-I$ degrés de liberté sont associés à la somme des carrés des résidus du modèle.\n\n## Décomposition de la variabilité\n\n<!-- ![](images/decomp_anova_hospital.png){width=\"50%\" fig-align=\"center\" height=\"250\"} -->\n\n::: {.cell}\n\n:::\n\n::::::::::: {layout=\"[ 32, 2, 32, 2, 32 ]\"}\n:::: {#first-column}\n::: r-stack\n![](images/plot_waiting_time_hospital.png){.fragment}\n\n![](images/plot_ss_anova.png){.fragment}\n:::\n::::\n\n::::: {#second-column}\n:::: fragment\n::: {style=\"font-size: 300%;\"}\n{{< fa equals size=4xl >}}\n:::\n::::\n:::::\n\n![](images/plot_bss_anova.png){.fragment}\n\n<div>\n\n:::: fragment\n::: {style=\"font-size: 300%;\"}\n{{< fa plus size=4xl >}}\n:::\n::::\n\n</div>\n\n![](images/plot_wss_anova.png){.fragment}\n:::::::::::\n\n. . .\n\n**Equation d'analyse de la variance**\n\n\\begin{tabular}{cccc}\n &$\\displaystyle{\\underbrace{\\sum_{i,j}(Y_{ij}-Y_{\\bullet \\bullet})^2}_{SC_T}}$&$= \\displaystyle{\\underbrace{\\sum_{i}n_i(Y_{i\\bullet}-Y_{\\bullet \\bullet})^2}_{SC_F}}$&$+ \\displaystyle{\\underbrace{\\sum_{i,j}(Y_{ij}-Y_{i\\bullet})^2}_{SC_R}}$\\\\\nVariabilité &totale&modèle&résiduelle\\\\\nddl&$n-1$&$I-1$&$n-I$\\\\\n\\end{tabular}\n\n. . .\n\n-   Vous pouvez commencez à comprendre d'où vient le nom ANalysis Of **VAriance**\n\n## Indicateur de liaison : rapport de corrélation\n\n. . .\n\n$\\eta^2  = \\frac{SC_{\\mbox{modèle}}}{SC_{\\mbox{total}}} = 1-\\frac{SC_{\\mbox{résiduelle}}}{SC_{\\mbox{total}}}$\n\n> Expliqué à mon grand-père (ou presque): la proportion de variabilité du phénomène que mon modèle explique\n\n. . .\n\nPropriétés:\n\n-   $0 \\leq \\eta^2 \\leq 1$ (obvious)\n-   $\\eta^2 = 0 \\Leftrightarrow SC_{\\mbox{modèle}}=0$\n-   $\\eta^2=1 \\Leftrightarrow SC_{\\mbox{modèle}}=SC_{\\mbox{total}}$\n\n. . .\n\n::: {.cell}\n\n:::\n\n::::: columns\n::: {.column width=\"50%\"}\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-43-1.png){width=451.2}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-44-1.png){width=451.2}\n:::\n:::\n:::\n:::::\n\n::: {style=\"text-align: center;\"}\nDeux rapports de corrélation différents pour des $Y_{i\\bullet}$ identiques.\n:::\n\n## Inférence: test global\n\nRappel de l'objectif: y a-t-il un effet du facteur sur Y ?\n\n. . .\n\n$\\rightarrow$ La variabilité de Y est-elle expliquée par le facteur groupe ? Ou bien peut-on considérer que les données proviennt d'une même loi $\\mathcal{N}(\\mu, \\sigma^2)$ ?\n\n. . .\n\n::::::: columns\n::: {.column width=\"20%\"}\n**Hypothèses:**\n:::\n\n::: {.column width=\"36%\"}\n$$H_0 :~\\forall i,\\ \\mu_i=\\mu$$ $$H_1 :~\\exists i\\ /\\ \\mu_i\\ne \\mu$$\n:::\n\n::: {.column width=\"8%\"}\n$\\Leftrightarrow$\n:::\n\n::: {.column width=\"36%\"}\n$$H_0 :~\\forall i,\\ \\alpha_i=0$$ $$H_1 :~\\exists i\\ /\\ \\alpha_i\\ne 0$$\n:::\n:::::::\n\n$$\\mbox{On a : }\\mathbb{E}\\left(\\frac{SC_{mod}}{I-1}\\right)=\\sigma^2+\\frac{1}{I-1}\\displaystyle{\\sum_{i=1}^I n_i\\alpha_i^2} \\quad ;\\quad    \\mathbb{E}\\left(\\frac{SC_{R}}{n-I}\\right)=\\sigma^2$$\n\n. . .\n\n::::: columns\n::: {.column width=\"50%\"}\n-   **Statistique de test** : $F_{obs}=\\displaystyle{\\frac{SC_{mod}/(I-1)}{SC_{R}/(n-I)}}$\n\n-   **Loi de** $F_{obs}$ sous $H_0$ : ${\\mathcal L}(F_{obs})={\\mathcal F}_{n-I}^{I-1}$\n:::\n\n::: {.column width=\"50%\"}\n![](images/fisher_anova.png){width=\"80%\" fig-align=\"center\" height=\"250\"}\n:::\n:::::\n\n## Table d'analyse de variance: décomposition de variabilité et test\n\n-   Ce qui est souvent reporté dans le cadre d'une ANOVA\n\n\\begin{center}\n\\begin{tabular}{|c|c|c|c|c|} \\hline\n\\bf Variabilité & \\bf Somme Carrés  & \\bf ddl&\\bf Carré moyen&$F_{obs}$ \\\\\n\\hline\nFacteur &  $\\displaystyle{\\sum_in_i(Y_{i\\bullet}-Y_{\\bullet\\bullet})^2} $ & $I-1$ & $\\displaystyle{\\frac{SC_F}{I-1}}$&$\\displaystyle{\\frac{CM_F}{CM_R}}$\\\\\n\\hline\nRésiduelle & $ \\displaystyle{\\sum_{i,j}(Y_{ij}-Y_{i\\bullet})^2} $ & $n-I$ &$\\displaystyle{\\frac{SC_R}{n-I}}$&\\\\\n\\hline\nTotale & $\\displaystyle{\\sum_{i,j}(Y_{ij}-Y_{\\bullet \\bullet})^2}$ & $n-1$&& \\\\\n  \\hline\n\\end{tabular}\n\\end{center}\n\n. . .\n\n::::: columns\n::: {.column width=\"60%\"}\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\nLinearModel(maxO3 ~vent, data = ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nLinearModel(formula = maxO3 ~ vent, data = ozone)\n\nResidual standard error: 27.32 on 108 degrees of freedom\nMultiple R-squared:  0.08602 \nF-statistic: 3.388 on 3 and 108 DF,  p-value: 0.02074 \nAIC = 744.8    BIC = 755.7\n\nFtest\n             SS  df      MS F value  Pr(>F)\nvent       7586   3 2528.69  3.3881 0.02074\nResiduals 80606 108  746.35                \n\nTtest\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)   94.7382     3.0535 31.0265  < 2e-16\nvent - Est    10.8618     6.8294  1.5904  0.11466\nvent - Nord   -8.6092     4.6219 -1.8627  0.06522\nvent - Ouest -10.0382     4.0972 -2.4500  0.01589\nvent - Sud     7.7856     5.2052  1.4957  0.13764\n```\n\n\n:::\n:::\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-46-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n## Inférence: test de conformité d'un coefficient (1/2)\n\nSi on rejette l'hypothèse $H_0: \\forall i, \\alpha_i=0$, on veut savoir quels $\\alpha_i$ sont différents de 0\n\n\\vfill\n\nLa valeur de $\\hat\\alpha_i$ dépend de l'échantillon de données et donc l'estimateur $\\hat\\alpha_i$ est une variable aléatoire $${\\cal L}(\\hat\\alpha_i)={\\cal N}\\left(\\alpha_i,\\sigma_{\\hat\\alpha_i}^2\\right)~~\\Longleftrightarrow~~{\\cal L}\\left(\\frac{\\hat\\alpha_i-\\alpha_i}{\\sigma_{\\hat\\alpha_i}}\\right)={\\cal N}(0,1)$$\n\n. . .\n\n$${\\cal L}\\left(\\frac{\\hat\\alpha_i-\\alpha_i}{\\hat\\sigma_{\\hat\\alpha_i}}\\right)={\\cal T}_{n-I}$$\n\nOn peut donc construire le test de nullité d'un coefficient ($\\alpha_1$ par exemple):\n\n**Hypothèses** : $H_0 : \\alpha_1=0$ contre $H_1 : \\alpha_1 \\ne 0$\n\n**Statistique de test** $\\displaystyle\\frac{\\hat\\alpha_1}{\\hat\\sigma_{\\hat\\alpha_1}}$\n\n**Loi de la statistique de test sous** $H_0$ ${\\cal L}\\left(T_{obs}=\\frac{\\hat\\alpha_1}{\\hat\\sigma_{\\hat\\alpha_1}}\\right)={\\cal T}_{\\nu=n-I}$\n\n**Décision** par la p-value\n\n. . .\n\nRq : connaissant la loi de $\\hat\\alpha_1$, on peut construire un intervalle de confiance: $$\\alpha_1 \\in \\left[\\hat\\alpha_1-\\hat\\sigma_{\\hat\\alpha_1}\\times t_{0.975}(n-I)~;~\\hat\\alpha_1+\\hat\\sigma_{\\hat\\alpha_1}\\times t_{0.975}(n-I) \\right]$$\n\n## Inférence: test de conformité d'un coefficient (2/2)\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error   t value     Pr(>|t|)\n(Intercept)   94.738210   3.053461 31.026504 1.290980e-55\nvent - Est    10.861790   6.829425  1.590440 1.146587e-01\nvent - Nord   -8.609178   4.621850 -1.862713 6.522029e-02\nvent - Ouest -10.038210   4.097207 -2.450013 1.589160e-02\nvent - Sud     7.785599   5.205173  1.495743 1.376372e-01\n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell output-line-numbers='3'}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\nres <- LinearModel(maxO3 ~vent, data = ozone)\n\nres$Ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.highlight .numberLines}\n               Estimate Std. Error   t value     Pr(>|t|)\n(Intercept)   94.738210   3.053461 31.026504 1.290980e-55\nvent - Est    10.861790   6.829425  1.590440 1.146587e-01\nvent - Nord   -8.609178   4.621850 -1.862713 6.522029e-02\nvent - Ouest -10.038210   4.097207 -2.450013 1.589160e-02\nvent - Sud     7.785599   5.205173  1.495743 1.376372e-01\n```\n\n\n:::\n:::\n\n\n## Test de comparaison 2 à 2\n\nAutre stratégie : comparer toutes les paires de moyennes\n\nPb : on effectue beaucoup de tests $\\Rightarrow$ risque de multiplier les erreurs en rejetant des hypothèses $H_0$.\n\n$\\Rightarrow$ correction des tests: modifier le seuil $\\alpha =5\\%$ et prendre $\\alpha=\\frac{5\\%}{(\\mbox{nb tests)}}$\n\n$\\Rightarrow$ les tests sont peu puissants\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\n\n\nres <- LinearModel(maxO3 ~vent, data = ozone)\n\nmeansComp(res, ~vent, adjust =\"Bonferroni\", graph = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$adjMean\n vent  emmean   SE  df lower.CL upper.CL\n Est    105.6 8.64 108     83.7    127.5\n Nord    86.1 4.91 108     73.7     98.6\n Ouest   84.7 3.86 108     74.9     94.5\n Sud    102.5 5.96 108     87.4    117.7\n\nConfidence level used: 0.95 \nConf-level adjustment: bonferroni method for 4 estimates \n\n$groupComp\n$groupComp$Letters\nOuest  Nord   Sud   Est \n  \"a\"   \"a\"   \"a\"   \"a\" \n\n$groupComp$LetterMatrix\n         a\nOuest TRUE\nNord  TRUE\nSud   TRUE\nEst   TRUE\n\n\nattr(,\"class\")\n[1] \"meansComp\"\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-50-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n## Analyse des résidus du modèle {.scrollable}\n\n::: {style=\"font-size: 70%;\"}\n**Rappel du modèle:**\n\n$$ \\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\mu_i+ \\varepsilon_{ij}\\\\\n\\forall i,j~~~~{\\cal L}(\\varepsilon_{ij})={\\cal N}(0,\\sigma^2)\\\\\n\\forall (i,j)\\neq (i',j')~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right. $$\n\n-   On a des hypothèses sur les *résidus* du modèle\n\n-   Les résidus, c'est ce qui n'est pas expliqué par le modèle. Donc pour les estimer, il faut *ajuster* le modèle\n:::\n\n. . .\n\n::: {style=\"font-size: 80%;\"}\nOn peut ensuite vérifier les hypothèses du modèle\n:::\n\n. . .\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nresidus <- data.frame(residus=res$lmResult$residuals, vent = ozone$vent)\nresidus %>% \n  ggplot(aes(x=residus))+\n  geom_histogram(fill=\"lightblue\", aes(y = after_stat(density)))+\n  theme_bw() +\n  labs(x  =\"Résidu\", y = \"Densité\", title = \"Histogramme des résidus\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-51-1.png){width=384}\n:::\n:::\n\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nresidus %>% \n  ggplot(aes(y=residus,x=vent,fill=vent))+\n  geom_boxplot(alpha = .5)+\n  labs(title = \"Boxplot des résidus par vent\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-52-1.png){width=384}\n:::\n:::\n\n\n# Régression linéaire simple\n\n## Liaison linéaire\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nozone %>% \n  ggplot(aes(x = T9, y= maxO3)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE) + # se= FALSE pour virer les\n  # intervalles de confiance, method = \"lm\" ajustement linéaire\n  labs(title = \"Lien entre température à 9°C et maximum d'ozone\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-53-1.png){width=480}\n:::\n:::\n\n\n. . .\n\n**Questions** {{< fa question size=1xl >}}\n\n-   Influence de la température sur le max d'ozone ?\n-   A quel max d'ozone peut-on s'attendre s'il fait 19.5°C à 9h ?\n\n. . .\n\n**Objectifs** {{< fa bullseye size=1xl >}}\n\n-   Etudier qualitativement et quantitativement la dépendance d’une variable réponse quantitative Y en fonction d’une variable quantitative x\n\n-   La variable x permet elle d’expliquer la variabilité de la variable Y?\n\n-   Prédire Y à partir de x\n\n## Un autre indice de liaison: le coefficient de corrélation linéaire\n\n$$r_{xy}=\\frac{\\sum_{i=1}^n(x_i-\\bar x)(y_i-\\bar y)}{\\sqrt{\\sum_{i=1}^n\\left(x_i-\\bar x\\right)^2}\\sqrt{\\sum_{i=1}^n(y_i-\\bar y)^2}}$$\n\n::: incremental\n-   $-1\\leq r_{xy}\\leq 1$\n-   $r_{xy}=0 \\Leftrightarrow$ pas de liaison *linéaire* entre $X$ et $Y$\n-   $r_{xy}\\approx 1 \\Leftrightarrow$ relation *linéaire* croissante entre $X$ et $Y$\n-   $r_{xy}\\approx -1 \\Leftrightarrow$ relation *linéaire* décroissante entre $X$ et $Y$\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(ozone$maxO3, ozone$T9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  ozone$maxO3 and ozone$T9\nt = 10.263, df = 110, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5904575 0.7832906\nsample estimates:\n      cor \n0.6993865 \n```\n\n\n:::\n:::\n\n\n-   $r_{xy}= 0.70 \\ \\Rightarrow$ corrélation assez forte (et significativement différente de 0, mais on verra ça plus tard)\n\n## Corrélation, causalité etc. (1/2) {.scrollable}\n\n::: {style=\"font-size: 80%;\"}\n-   Une corrélation est un indicateur utile, mais à utiliser avec précaution\n\n\n::: .columns\n\n::: {.column width=\"45%\"}\n\n::: .fragment\n\n> \"Corrélation n'implique pas causalité\"\n\n:::\n\n:::\n\n\n::: {.column width=\"55%\"}\n\n\n::: r-stack\n\n![](images/causality_shoes_0.png){.fragment}\n\n![](images/causality_shoes_1.png){.fragment}\n\n![](images/causality_shoes_2.png){.fragment}\n\n<!-- ![](images/causality_shoes_3.png){.fragment} -->\n\n:::\n\n:::\n\n:::\n\n:::\n\n. . .\n\n::: {style=\"font-size: 80%;\"}\nOui, mais... la présence d'une corrélation suppose généralement un lien\n:::\n\n. . .\n\n:::: {style=\"font-size: 80%;\"}\n-   Ex. on observe une corrélation entre A et B. Plusieurs cas existent.\n\n::: incremental\n-   A $\\Rightarrow$ B (ex. {{< fa smoking size=1xl >}} $\\Rightarrow$ cancer {{< fa lungs size=1xl >}})\n\n-   B $\\Rightarrow$ A (idem)\n\n-   A $\\Rightarrow$ B et *ET* B $\\Rightarrow$ A (ex. {{< fa temperature-high size=1xl >}} et $CO_2$ )\n\n-   Une variable C a été omise, et influence A et B. (ex. {{< fa sun size=1xl >}} (C) $\\Rightarrow$ {{< bi sunglasses >}} (A),{{< fa sun size=1xl >}} (C) $\\Rightarrow$ {{< fa ice-cream size=1xl >}} (B), {{< fa ice-cream size=1xl >}} $\\Leftrightarrow$ {{< bi sunglasses >}})\n\n-   Corrélation purement fortuite (site [spurious correlations](https://www.tylervigen.com/spurious-correlations){style=\"color:blue;\"})\n:::\n::::\n\n## Corrélation, causalité etc. (2/2)\n\n::: {style=\"font-size: 80%;\"}\nEx. pour rigoler:\n:::\n\n::::: columns\n::: {.column width=\"45%\"}\n![](images/spurious_cor.svg){fig-align=\"center\" width=\"100%\"}\n:::\n\n::: {.column width=\"45%\"}\n![](images/spurious_cor2.svg){fig-align=\"center\" width=\"100%\"}\n:::\n:::::\n\n. . .\n\n::: {style=\"font-size: 90%;\"}\n> \"Corrélation n'implique pas causalité\"\n\nOk, mais cette affirmation ne doit pas servir à réfuter toute association constatée dans des données.\n:::\n\n## Quelques valeurs de corrélations\n\n![](images/illu_corr.jpg){width=\"80%\" fig-align=\"center\" height=\"550\"}\n\n\n::: {.cell}\n\n:::\n\n\n## (Re)Mettons les mains dans le cambouis\n\nLe modèle de régression linéaire simple s'écrit ainsi:\n\n. . .\n\n$$Y_{i} = \\beta_0 +\\beta_1 x_{i}  +\\varepsilon_{i},\\quad \\varepsilon_{i}\\overset{ind}{\\sim}\\mathcal{N}(0, \\sigma^2),$$ avec\n\n-   $x_i$ la valeur de la variable explicative pour l'observation $i$\n-   $i=1,\\ldots,n$ le numéro d'individu, $n$ le nombre total d'individus\n-   $\\beta_0$ l'ordonnée à l'origine\n-   $\\beta_1$ la pente de la droite, mesure de l'effet de la variable $x$\n-   $\\sigma^2$ la variance\n\n## Estimation des paramètres\n\n::::::: columns\n::: {.column width=\"45%\"}\n$$SCER = \\sum_{i=1}^n (y_i - \\hat{y}_i)^2 = \\sum_{i=1}^n (y_i - \\beta_0 - \\beta_1 x_i)^2$$\n\n**Paramètres d'espérance:**\n\n-   $\\hat{\\beta_1} = \\frac{\\sum_{i=1}^n (x_i-\\bar x)(Y_i-\\bar{Y})}{\\sum_{i=1}^n (x_i - \\bar{x})^2}$\n-   $\\hat{\\beta_0} = \\bar{Y} - \\hat{\\beta_1}\\bar{x}$\n:::\n\n::::: {.column width=\"55%\"}\n::: r-stack\n![](images/MCO1_T9maxO3_page-0001.jpg){.fragment}\n\n![](images/MCO2_T9maxO3_page-0001.jpg){.fragment}\n:::\n\n::: fragment\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nres <- LinearModel(maxO3 ~ T9, data = ozone)\nres$Ttest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) -25.607608 11.4551179 -2.235473 2.740572e-02\nT9            6.312999  0.6151378 10.262740 9.729952e-18\n```\n\n\n:::\n:::\n\n:::\n:::::\n:::::::\n\n. . .\n\n**Variance résiduelle:**\n\n$$ \\hat{\\sigma}^2 = \\frac{1}{n-2} \\sum_{i=1}^n (Y_i-\\hat{Y}_i)^2 ~~~;~~~ddl_{\\mbox{résiduelle}}=n-2~~~;~~~\\mathbb{E}(\\hat\\sigma^2)=\\sigma^2 $$\n\n## Test de conformité\n\n$${\\mathcal L}\\left(\\hat{\\beta}_1\\right)  = {\\mathcal N}\\left( \\beta_1,\\sigma_{\\beta_1}^2\\right) \\mbox{  avec  } \\sigma_{\\beta_1}^2= \\frac{\\sigma^2}{\\sum_{i=1}^{n} ( x_{i} - \\bar{x} )^{2}} $$\n\n$$\\Longrightarrow \\ {\\mathcal L}\\left(\\frac{\\hat\\beta_1-\\beta_1}{\\sigma_{\\hat\\beta_1}}\\right)={\\mathcal N}(0,1)\n\\ \\Longrightarrow~~{\\mathcal L}\\left(\\frac{\\hat\\beta_1-\\beta_1}{\\hat\\sigma_{\\hat\\beta_1}}\\right)={\\mathcal T}_{n-2}$$\n\n. . .\n\nOn peut donc construire le test de nullité de $\\beta_1$:\n\n. . .\n\n**Hypothèses** :$\\ H_0 : \\mbox{\"} \\beta_1=0\\mbox{\"}$ contre $H_1 : \\mbox{\"} \\beta_1 \\ne 0\\mbox{\"}$\n\n**Statistique de test :** $\\displaystyle\\frac{\\hat\\beta_1}{\\hat\\sigma_{\\hat\\beta_1}}$ **Loi de la statistique de test sous** $H_0$: ${\\mathcal L}\\left(T_{obs}=\\frac{\\hat\\beta_1}{\\hat\\sigma_{\\hat\\beta_1}}\\right)={\\mathcal T}_{\\nu=n-2}$\n\nRq 1. : comme dans l'ANOVA, connaissant la loi de $\\hat\\beta_1$, on peut construire un intervalle de confiance: $$\\beta_1 \\in \\left[\\hat\\beta_1-\\hat\\sigma_{\\hat\\beta_1}\\times t_{0.975}(n-2) \\ ; \\ \\hat\\beta_1+\\hat\\sigma_{\\hat\\beta_1}\\times t_{0.975}(n-2) \\right]$$\n\nRq 2. : on peut aussi tester $\\beta_0$ mais cela a moins d'importance en pratique\n\n## Décomposition de la variabilité\n\n::: {.cell}\n\n:::\n\n::::::::::: {layout=\"[ 32, 2, 32, 2, 32 ]\"}\n<div>\n\n::: r-stack\n![](images/plot_ozone.png){.fragment}\n\n![](images/plot_SCT_ozone.png){.fragment}\n:::\n\n</div>\n\n<div>\n\n:::: fragment\n::: {style=\"font-size: 300%;\"}\n{{< fa equals size=4xl >}}\n:::\n::::\n\n</div>\n\n![](images/plot_SCM_ozone.png){.fragment}\n\n<div>\n\n:::: fragment\n::: {style=\"font-size: 300%;\"}\n{{< fa plus size=4xl >}}\n:::\n::::\n\n</div>\n\n![](images/plot_SCR_ozone.png){.fragment}\n:::::::::::\n\n. . .\n\n$$\\begin{array}{ccccc}\n   \\sum_{i=1}^{n} ( Y_{i} - \\bar{Y} )^{2} & = & \\sum_{i=1}^{n} ( \\hat{Y}_{i} - \\bar{Y} )^{2}\n   & + & \\sum_{i=1}^{n} ( Y_{i} - \\hat{Y}_{i} )^{2}  \\\\\n   SCT & = & SCM & + & SCR   \\\\\n   n - 1 & = & 1 & + & n - 2\n   \\end{array}$$\n\n## Table d'analyse de la variance\n\n<!-- **Table d'analyse de la variance** -->\n\n::::: columns\n::: {.column width=\"50%\"}\n<!-- \\begin{center} -->\n<!-- \\begin{tabular}{|c|c|c|c|c|} -->\n<!-- \\hline -->\n<!-- Source    & Somme de & Degrés de &  Carré & F \\\\ -->\n<!-- variation &  carrés &  liberté & moyen & \\\\ -->\n<!-- \\hline -->\n<!-- Modèle & SCM & 1 & $\\frac{SCM}{1}$ & $\\frac{CMM}{CMR}$\\\\ -->\n<!-- % & & & & \\\\ -->\n<!-- Erreur & SCR & n-2 &\\ $\\frac{SCR}{n-2}$ & \\\\ -->\n<!-- % & & & & \\\\ -->\n<!-- Total & SCT & n-1 &  & \\\\ -->\n<!-- \\hline -->\n<!-- \\end{tabular} -->\n<!-- \\end{center} -->\n\n| Source de variation | Somme des carrés | Degrés de liberté | Carré moyen         | F                    |\n|---------------------|------------------|--------------------|----------------------|----------------------|\n| Modèle              | SCM              | 1                  | $\\frac{SCM}{1}$      | $\\frac{CMM}{CMR}$    |\n| Erreur              | SCR              | $n-2$              | $\\frac{SCR}{n-2}$    |                      |\n| Total               | SCT              | $n-1$              |                      |                      |\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- LinearModel(maxO3 ~T9, data=  ozone)\nres$Ftest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             SS  df    MS F value    Pr(>F)    \nT9        43138   1 43138  105.32 < 2.2e-16 ***\nResiduals 45053 110   410                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n\n\n\n. . .\n\nComparaison de $SCM$ et $SCT$ par le critère $\\displaystyle{R^{2} = \\frac{ SCM }{ SCT } }$\n\n. . .\n\n**Propriétés :**\n\n-   $0\\leq R^2\\leq 1$\n-   $R^2 = 0 \\Leftrightarrow SC_{\\mbox{modéle}}=0$\n-   $R^2=1 \\Leftrightarrow SC_{\\mbox{modèle}}=SC_{\\mbox{total}}$\n\n**Explication claire du concept sur le [site](https://scienceetonnante.substack.com/p/quest-ce-quune-correlation-forte){style=\"color:blue;\"} de Science Etonnante**\n\n## Test du modèle\n\n**Hypothèses**\n\n-   $H_0: \\beta_1 = 0, \\Leftrightarrow$ le modèle n'a pas d'intérêt (x n'explique pas Y)\n-   $H_1: \\beta_1 \\neq 0, \\Leftrightarrow$ le modèle a un intérêt (x explique Y)\n\n. . .\n\n**Stat de Fisher**\n\n$F = \\frac{SCM/1}{SCR/(n-2)}$\n\n. . .\n\n**Loi de F sous** $H_0: \\mathcal{L}(F) = \\mathcal{F}^1_{n-2}$\n\n## Prédiction et intervalle de confiance\n\nPour une valeur de $x_0$ particulière, on peut maintenant prédire $Y$:\n\n$$\\hat{Y}_0  = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_0$$\n\n:::::: columns\n::: {.column width=\"50%\"}\nPrédiction de la valeur moyenne de Y pour un $x_0$ particulier\n\n$\\mathbb{E}(\\hat{Y}_0|x_0) \\sim \\mathcal{N}(Y_0, \\sigma \\sqrt{\\frac{1}{n} + \\frac{(x_0 - \\bar{x})^2}{\\sum_{i=1}^n (x_i - \\bar{x})^2}})$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>% \n  ggplot(aes(x = T9, y = maxO3)) +\n  geom_point() +\n  geom_smooth(method =\"lm\") +# affiche intervalle de confiance par défaut\n  theme_bw()+\n  labs(title = \"Intervalle de confiance du comportement moyen\")+\n  theme(text = element_text(size = 15))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-59-1.png){width=960}\n:::\n:::\n\n:::\n\n:::: {.column width=\"50%\"}\n::: fragment\n*Différent de:*\n\nPrédiction d'une nouvelle valeur de Y pour un $x_0$ donné (*notez le 1 supplémentaire dans la variance*).\n\n$\\hat{Y}_0 \\sim \\mathcal{N}(Y_0, \\sigma \\sqrt{1+\\frac{1}{n} + \\frac{(x_0 - \\bar{x})^2}{\\sum_{i=1}^n (x_i - \\bar{x})^2}})$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_predict <- bind_cols(data.frame(T9 = ozone$T9),  predict(lm(maxO3 ~ T9, data= ozone), interval = \"predict\"))\n\nozone %>% \n  ggplot(aes(x = T9, y = maxO3)) +\n  geom_point() +\n  geom_smooth(method =\"lm\") +# affiche intervalle de confiance par défaut\n  geom_ribbon(data = data_predict, aes(x = T9, ymax = upr, ymin = lwr, y = fit), alpha = .2, fill = \"blue\") + \n  theme_bw()+\n  labs(title = \"Intervalle de confiance du comportement moyen\") +\n  theme(text = element_text(size = 15))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-60-1.png){width=960}\n:::\n:::\n\n:::\n::::\n::::::\n\n## Validité du modèle\n\n**Vérification des hypothèses de départ:**\n\n-   Normalité des résidus, stabilité de la variance, indépendance des résidus\n\n![](images/aber.jpg){width=\"100%\" height=\"400\"}\n\n# Construction et sélection de modèle\n\n::::: {style=\"font-size: 140%;\"}\n## Modéliser = Comprendre et prévoir\n\n{{< fa question size=1xl >}} Des exemples de modélisation que vous effectuez tous les jours ?\n\n. . .\n\n::: incremental\n-   Budget pour évènement {{< fa dollar-sign size=1xl >}} {{< fa cake-candles size=1xl >}}\n-   {{< fa sun size=1xl >}} {{< fa shirt size=1xl >}} vs {{< fa snowflake size=1xl >}} {{< fa mug-hot size=1xl >}}\n-   {{< fa calendar-days size=1xl >}}\n:::\n\n. . .\n\n{{< fa question size=1xl >}} Comment faites-vous ?\n\n. . .\n\n-   Ex. estimation du budget d'une soirée d'anniversaire\n\n::: incremental\n-   Vous listez les variables ({{< fa people-group size=1xl >}} {{< fa beer-mug-empty size=1xl >}} {{< fa wine-bottle size=1xl >}} {{< fa pizza-slice size=1xl >}} {{< fa plug-circle-plus size=1xl >}} {{< fa droplet size=1xl >}} etc.)\n\n-   Vous éliminez celles qui sont négligeables (ex. {{< fa plug-circle-plus size=1xl >}} {{< fa droplet size=1xl >}})\n\n-   Vous quantifiez l'effet des variables restantes\n:::\n\n. . .\n\nLes statistiques permettent de faire cela avec des phénomènes complexes, en partant de données collectées.\n:::::\n\n:::: {style=\"font-size: 140%;\"}\n## Exemple de problématiques\n\n::: incremental\n-   Prévoir la sévérité d'une maladie fongique en fonction de la météo (P/ETP/T°) et de l'itk (gestion des résidus, sensibilité variétale etc;)\n\n-   Prédire les potentiels de rendements futurs du soja en France\n\n-   Potentiel de production éolien en fonction des conditions météorologiques\n:::\n\n. . .\n\n**Objectifs:**\n\n-   *Comprendre* quelles variables ont une influence sur une variable quanti\n\n-   *Prévoir* les valeurs de la variable réponse dans de nouvelles conditions\n::::\n\n## Régression simple vs multiple\n\n. . .\n\n-   En régression simple, on ne considérait *qu'une* seule variable explicative\n\n. . .\n\n-   En régression multiple, on en considère *plusieurs* (p)\n\n. . .\n\n$$\\mbox{Réponse} = f(var1, \\color{red}{var_2, ..., var_p}) =\\underbrace{var1 + \\color{red}{var_2 + ...+ var_p}}_{\\mbox{régression linéaire}}$$\n\n$$ \\left\\{\n\\begin{array}{l}\n\\forall i=1,...,n~~~~\\varepsilon_i ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_i)=0,~~\\mathbb{V}(\\varepsilon_i)=\\sigma^2\\\\\n\\forall i\\neq k~~~~cov(\\varepsilon_i,\\varepsilon_{k})=0\\\\\n\\end{array}\\right. $$\n\n## Une variable quanti peut avoir un effet différent selon différentes modalités d'une quali\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nozone %>% \n  ggplot(aes(x = T9, y = maxO3, color = vent))+\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Effet de T9 sur l'ozone selon les directions du vent\") +\n  theme_bw() + \n  theme(text = element_text(size = 15))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-61-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nCela s'écrit ainsi:\n\n::: {style=\"font-size: 75%;\"}\n\n$$MaxO3 \\sim vent + T9 + \\mbox{vent:T9}$$\n\n$$MaxO3_{ij} \\sim \\mu+\\left\\{ \\begin{array}{l}\n\\alpha_{1} ~\\mbox{si vent d'est} \\\\\n\\alpha_{2} ~\\mbox{si vent du nord} \\\\\n\\alpha_{3} ~\\mbox{si vent d'ouest} \\\\\n\\alpha_{4} ~\\mbox{si vent du sud} \\\\\n\\end{array}\n\\right\\} ~~+~~ \\left(\\beta+\\left\\{ \\begin{array}{l}\n\\gamma_{1} ~\\mbox{si vent d'est} \\\\\n\\gamma_{2} ~\\mbox{si vent du nord} \\\\\n\\gamma_{3} ~\\mbox{si vent d'ouest} \\\\\n\\gamma_{4} ~\\mbox{si vent du sud} \\\\\n\\end{array}\n\\right\\}\\right)\\times T9{ij}+ alea_{ij}$$ \n$$\\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\mu+\\alpha_i+(\\beta+\\gamma_i)\\times x_{ij} + \\varepsilon_{ij}\\\\\n\\forall i,j~~~~\\varepsilon_{ij} ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_{ij})=0,~~\\mathbb{V}(\\varepsilon_{ij})=\\sigma^2\\\\\n\\forall i,j~~~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right. $$\n:::\n\n## Interaction entre deux variables qualitatives\n\n::: {.fragment .strike}\n**Définition courante**: réaction réciproque de deux phénomènes l’un sur l’autre\n:::\n\n::: fragment\n**Définition statistique** : l’effet d’un facteur sur Y diffère selon les modalités de l’autre facteur\n:::\n\n. . .\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nozone %>%\n  group_by(vent, pluie) %>%\n  summarize(MOY = mean(maxO3)) %>%\n  ggplot(aes(x=vent, y=MOY, col=pluie, group=pluie)) +\n  geom_line() +\n  geom_point() +\n  labs(\"Interaction pluie:vent sur maxO3\", x = \"Direction du vent\", y = \"Maximum d'ozone\") +\n  theme_bw()+ \n  theme(text = element_text(size = 18))\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError: <ggplot2::labels> object is invalid:\n- every label must be named.\n```\n\n\n:::\n:::\n\n\n. . .\n\nCela s'écrit ainsi:\n\n::: {style=\"font-size: 73%;\"}\n$$MaxO3 \\sim vent + pluie + \\mbox{vent:pluie}$$ $$MaxO3_{ijk} \\sim \\mu+\\left\\{ \\begin{array}{l}\n\\alpha_{1} ~\\mbox{si vent d'est} \\\\\n\\alpha_{2} ~\\mbox{si vent du nord} \\\\\n\\alpha_{3} ~\\mbox{si vent d'ouest} \\\\\n\\alpha_{4} ~\\mbox{si vent du sud} \\\\\n\\end{array}\n\\right\\} + \\left\\{ \\begin{array}{l}\n\\beta_{1} ~\\mbox{si pluie} \\\\\n\\beta_{2} ~\\mbox{si sec} \\\\\n\\end{array}\n\\right\\} +\n\\left\\{ \\begin{array}{l}\n\\alpha\\beta_{11} ~\\mbox{si vent d'est ET pluie} \\\\\n\\alpha\\beta_{12} ~\\mbox{si vent d'est ET sec} \\\\\n\\alpha\\beta_{21} ~\\mbox{si vent du nord ET pluie} \\\\\n\\cdots\n\\alpha\\beta_{42} ~\\mbox{si vent du sud ET sec} \\\\\n\\end{array}\n\\right\\} + alea_{ijk}$$\n\n$$\\left\\{\n\\begin{array}{l}\n\\forall i,j,k~~~~Y_{ijk}=\\mu+\\alpha_i+\\beta_j +\\alpha\\beta_{ij} +\\varepsilon_{ijk}\\\\\n\\forall i,j,k~~~~\\varepsilon_{ijk} ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_{ijk})=0,~~\\mathbb{V}(\\varepsilon_{ijk})=\\sigma^2\\\\\n\\forall i,j,k~~~~cov(\\varepsilon_{ijk},\\varepsilon_{i'j'k'})=0\\\\\n\\end{array}\\right. $$ \n\n:::\n\n------------------------------------------------------------------------\n\n**Quatres types d'effet possibles**\n\n:::::::::: {style=\"font-size: 75%;\"}\n::::::::: {layout-nrow=\"2\"}\n::::: {layout-ncol=\"2\"}\n<div>\n\n\n::: {.cell layout-align=\"center\" output-location='fragment'}\n\n```{.r .cell-code  code-fold=\"true\"}\ntheme_set(theme_bw())\n\nozone %>%\n  ggplot(aes(x = T9, y = maxO3)) +\n  geom_point() +\n  geom_smooth(method =\"lm\", se= FALSE) +\n  labs(title = \"Quanti sur quanti\")+ \n  theme(text = element_text(size = 18))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-63-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n</div>\n\n<div>\n\n\n::: {.cell layout-align=\"center\" output-location='fragment'}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>%\n  ggplot(aes(x = vent, y = maxO3, color = vent)) +\n  geom_point(position= position_jitter(width =.05, height= 0)) +\n  geom_boxplot(alpha= .3, outlier.shape = NA) +\n  labs(title = \"Quali sur quanti\") +\n  theme_bw()+ \n  theme(text = element_text(size = 18))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-64-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n</div>\n:::::\n\n::::: {layout-ncol=\"2\"}\n<div>\n\n\n::: {.cell .fig-cap-location-top layout-align=\"center\" output-location='fragment'}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>%\n  ggplot(aes(x = T9, y = maxO3, color = vent))+\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Quali / quanti sur quanti\") +\n  theme_bw()+ \n  theme(text = element_text(size = 18))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-65-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n</div>\n\n<div>\n\n\n::: {.cell layout-align=\"center\" output-location='fragment'}\n\n```{.r .cell-code  code-fold=\"true\"}\nozone %>%\n  group_by(vent, pluie) %>%\n  summarize(MOY = mean(maxO3)) %>%\n  ggplot(aes(x=vent, y=MOY, col=pluie, group=pluie)) +\n  geom_line() +\n  geom_point() +\n  labs(title = \"Quali / quali sur quanti\", y = \"maxO3\") +\n  theme_bw()+ \n  theme(text = element_text(size = 18))\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-66-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n</div>\n:::::\n:::::::::\n::::::::::\n\n## Le(s) modèle(s) linéaire(s)\n\n. . .\n\n> Le modèle linéaire peut souvent être adapté à des problèmes issu du vivant, modulo quelques points de vigilance\n\n. . .\n\n\\begin{tabular}{llp{5.5cm}}\n\\hline\n && \\\\\n\\textbf{Réponse} & \\textbf{Variable(s) explicative(s)} & \\textbf{Méthode}\\\\\n\nVar. quantitative&1 var. quantitative & régression linéaire simple\\\\\nVar. quantitative&1 var. qualitative à $I$ modalités& analyse de variance à 1 facteur (rq: si $I=2$ équivaut à comparaison de 2 moyennes)}\\\\\nVar. quantitative&$p$ var. quantitatives & régression linéaire multiple}\\\\\nVar. quantitative&$K$ var. qualitatives & analyse de variance à $K$ facteurs}\\\\\nVar. quantitative & var. quantitatives et qualitatives& analyse de covariance\\\\\n\n\\hline\n\n\\textcolor{lightgray}{Var. qualitative (2 catégories)}& \\textcolor{lightgray}{var. quantitatives et qualitatives}& \\textcolor{lightgray}{régression logistique}\\\\\n\\textcolor{lightgray}{Var. qualitative (K catégories)}& \\textcolor{lightgray}{var. quantitatives et qualitatives}& \\textcolor{lightgray}{régression multinomiale}\\\\\n\\hline\n\\end{tabular}\n\n## (Re-Re)mettons les mains dans le cambouis\n\n$$\\left\\{\n\\begin{array}{l}\n\\forall i=1,...,n~~~~Y_i=\\color{red}{\\beta_0}+\\color{red}{\\beta_1}x_{i1}+\\color{red}{\\beta_2}x_{i2}+\\color{red}{\\beta_3}x_{i3}+...+\\color{red}{\\beta_p}x_{ip} + \\varepsilon_{i}\\\\\n\\forall i=1,...,n~~~~\\varepsilon_i ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_i)=0,~~\\mathbb{V}(\\varepsilon_i)=\\sigma^2\\\\\n\\forall i\\neq k~~~~cov(\\varepsilon_i,\\varepsilon_{k})=0\\\\\n\\end{array}\\right. $$\n\n\\textcolor{red}{(p+1) paramètres à estimer} + 1 paramètre de variance $\\sigma^2$\n\n. . .\n\n**Matriciellement** : $\\displaystyle{Y=X\\beta+E~~~~\\mbox{avec}~~\\mathbb{E}(E)=0,~~\\mathbb{V}(E)=\\sigma^2 Id}$\n\n\\scriptsize\n\n$$\n\\left(\n\\begin{array}{c}\nY_1\\\\\n\\vdots \\\\\nY_i \\\\\n\\vdots \\\\\nY_n \\\\\n\\end{array} \\right) =\n\\overset{{\\color{gray}{\\begin{matrix}{\\beta_0}  & {\\beta_1}& \\beta_2&\\ldots &\\beta_p\\end{matrix}}}}{\n\\left(\n\\begin{array}{cccccc}\n1 & x_{11} & x_{12}& \\cdots & x_{1p}\\\\\n\\vdots & & \\vdots& & \\vdots \\\\\n1 & x_{i1} & x_{i2}& & x_{ip} \\\\\n\\vdots & \\vdots & \\vdots& & \\vdots \\\\\n1 & x_{n1} & x_{n2}& \\cdots & x_{np}\\\\\n\\end{array} \\right)}\n\\left(\n\\begin{array}{c}\n\\color{red}{\\beta_0}\\\\\n\\color{red}{\\beta_1}\\\\\n\\color{red}{\\beta_2} \\\\\n\\vdots \\\\\n\\color{red}{\\beta_p} \\\\\n\\end{array} \\right) +\n\\left(\n\\begin{array}{c}\n\\varepsilon_1\\\\\n\\vdots \\\\\n\\varepsilon_i \\\\\n\\vdots \\\\\n\\varepsilon_n \\\\\n\\end{array} \\right)$$\n\n. . .\n\nRq: ANOVA et ANCOVA peuvent aussi s'écrire sous cette forme.\n\n:::::: {style=\"font-size: 95%;\"}\n::::: columns\n::: {.column width=\"50%\"}\n### ANOVA\n\n$$\\left\\{\n\\begin{array}{l}\n\\forall i,j,k~~~~Y_{ijk}=\\color{red}{\\mu}+\\color{red}{\\alpha_i}+\\color{red}{\\beta_j} +\\color{red}{\\alpha\\beta_{ij}} +\\varepsilon_{ijk}\\\\\n\\forall i,j,k~~~~\\varepsilon_{ijk} ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_{ijk})=0,~~\\mathbb{V}(\\varepsilon_{ijk})=\\sigma^2\\\\\n\\forall i,j,k~~~~cov(\\varepsilon_{ijk},\\varepsilon_{i'j'k'})=0\\\\\n\\end{array}\\right.$$\n:::\n\n::: {.column width=\"50%\"}\n### ANCOVA\n\n$$\\left\\{\n\\begin{array}{l}\n\\forall i,j~~~~Y_{ij}=\\color{red}{\\mu}+\\color{red}{\\alpha_i}+(\\color{red}{\\beta}+\\color{red}{\\gamma_i})\\times x_{ij} + \\varepsilon_{ij}\\\\\n\\forall i,j~~~~\\varepsilon_{ij} ~~\\mbox{i.i.d.}~~,~~\\mathbb{E}(\\varepsilon_{ij})=0,~~\\mathbb{V}(\\varepsilon_{ij})=\\sigma^2\\\\\n\\forall i,j~~~~cov(\\varepsilon_{ij},\\varepsilon_{i'j'})=0\\\\\n\\end{array}\\right.$$\n:::\n:::::\n::::::\n\n## Estimation des paramètres du modèle\n\n**Critère des moindres carrés**: estimer les paramétres en minimisant la somme des carrés des écarts entre observations et prévisions par le modéle\n\n<!-- %\\uncover<2->{ \\scriptsize -->\n\n<!-- %Dérivée matricielle par rapport é $\\beta$ (régles de dérivation: $\\frac{\\partial (A'Z)}{\\partial A} =\\frac{\\partial (Z'A)}{\\partial A}=Z$) -->\n\n<!-- % -->\n\n<!-- %\\vskip -0.5cm -->\n\n<!-- % -->\n\n<!--    %\\begin{eqnarray*} -->\n\n<!--    %0&=&\\frac{\\partial\\|Y-X\\beta\\|^2}{\\partial \\beta} = \\frac{\\partial (Y-X\\beta)'(Y-X\\beta)}{\\partial \\beta} \\\\ -->\n\n<!--    %&=& \\frac{\\partial (Y'Y-Y'X\\beta-\\beta'X'Y+\\beta'X'X\\beta)}{\\partial \\beta} =-X'Y-X'Y+X'X\\beta+X'X\\beta\\\\ -->\n\n<!-- %&\\Longrightarrow  &X^{\\prime}X \\hat\\beta = X^{\\prime}Y\\\\ -->\n\n<!--    %\\end{eqnarray*} -->\n\n<!-- % -->\n\n<!--    %\\vskip -1cm -->\n\n<!-- %} -->\n\n. . .\n\n$$Y\\approx X\\beta$$ $$X'Y\\approx X'X\\beta$$ \\normalsize $$\\color{red}{\\hat\\beta = (X^{\\prime}X)^{-1}X^{\\prime}Y} ~~\\mbox{si }X^{\\prime}X\\mbox{ est inversible}$$\n\n**Propriétés** $\\mathbb{E}(\\hat\\beta)=\\beta; \\ \\mathbb{V}(\\hat\\beta)=(X^{\\prime}X)^{-1}\\sigma^2$\n\n. . .\n\nLa variance des résidus $\\sigma^2$ est estimée par: $$\\hat \\sigma^2=\\frac{\\sum_{i}(Y_{i}-\\hat Y_{i})^2}{\\mbox{nb données} - \\mbox{nb paramétres estimés à partir des données}}~~~~~~~~~~\\mathbb{E}(\\hat\\sigma^2)=\\sigma^2$$\n\n## Décomposition de la variabilité (bis)\n\n. . .\n\n\\begin{tabular}{cccc}\n &$\\displaystyle{\\sum_{i=1}^n(y_i-\\bar y)^2}$&$= \\displaystyle{\\sum_{i=1}^n(\\hat y_i-\\bar y)^2}$&$+ \\displaystyle{\\sum_{i=1}^n(y_i-\\hat y_i)^2}$\\\\\nVariabilité &totale&modèle&résiduelle\\\\\n\\end{tabular}\n\n. . .\n\n**Pourcentage de variabilité de** $Y$ expliquée par le modèle: $R^2 = \\frac{SC_{modele}}{SC_{totale}}$\n\nPropriétés: $R^2 \\in [0,1]$.\n\n. . .\n\nLa variabilité du modèle peut être décomposée par variable de 2 façons:\n\n-   en calculant la variabilité expliquée par chaque variable les unes aprés les autres (pb : la variabilité d'une variable dépend de l'ordre d'introduction des variables)\n\n-   en calculant la variabilité expliquée exclusivement par une variable (pb : la somme des variabilités de toutes les variables n'est pas égale à la variabilité du modèle)\n\n. . .\n\nDans certains cas (données équilibrées), la variabilité du modéle se décompose parfaitement et ces 2 calculs donnent les mêmes résultats.\n\n## Exemple sur ozone\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\nLinearModel(maxO3~T9+T12+T15+Ne9+Ne12+Ne15+Vx9+Vx12+Vx15+maxO3v+vent+pluie, data =ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nLinearModel(formula = maxO3 ~ T9 + T12 + T15 + Ne9 + Ne12 + Ne15 + \n    Vx9 + Vx12 + Vx15 + maxO3v + vent + pluie, data = ozone)\n\nResidual standard error: 14.51 on 97 degrees of freedom\nMultiple R-squared:  0.7686 \nF-statistic: 23.01 on 14 and 97 DF,  p-value: 8.744e-25 \nAIC =   613    BIC = 653.8\n\nFtest\n               SS df     MS F value    Pr(>F)\nT9            0.2  1    0.2  0.0011   0.97325\nT12         376.0  1  376.0  1.7868   0.18445\nT15          30.3  1   30.3  0.1439   0.70526\nNe9        1016.5  1 1016.5  4.8312   0.03033\nNe12         37.9  1   37.9  0.1803   0.67208\nNe15          0.1  1    0.1  0.0003   0.98680\nVx9          50.2  1   50.2  0.2388   0.62619\nVx12         35.7  1   35.7  0.1697   0.68127\nVx15        122.6  1  122.6  0.5826   0.44715\nmaxO3v     5560.4  1 5560.4 26.4261 1.421e-06\nvent        297.8  3   99.3  0.4718   0.70267\npluie       182.9  1  182.9  0.8694   0.35344\nResiduals 20410.2 97  210.4                  \n\nTtest\n               Estimate Std. Error t value  Pr(>|t|)\n(Intercept)   20.762962  15.461879  1.3428   0.18245\nT9             0.039170   1.164957  0.0336   0.97325\nT12            1.972574   1.475705  1.3367   0.18445\nT15            0.450308   1.187073  0.3793   0.70526\nNe9           -2.109755   0.959855 -2.1980   0.03033\nNe12          -0.605592   1.426338 -0.4246   0.67208\nNe15          -0.017178   1.035894 -0.0166   0.98680\nVx9            0.482609   0.987624  0.4887   0.62619\nVx12           0.513795   1.247167  0.4120   0.68127\nVx15           0.726623   0.951976  0.7633   0.44715\nmaxO3v         0.344378   0.066991  5.1406 1.421e-06\nvent - Est    -2.874041   5.157999 -0.5572   0.57867\nvent - Nord   -2.334477   2.890844 -0.8075   0.42133\nvent - Ouest   2.662276   3.658288  0.7277   0.46853\nvent - Sud     2.546243   3.061435  0.8317   0.40761\npluie - Pluie -1.623565   1.741257 -0.9324   0.35344\npluie - Sec    1.623565   1.741257  0.9324   0.35344\n```\n\n\n:::\n\n```{.r .cell-code}\n# LinearModel(maxO3 ~. , data=  ozone) ## Ecriture simplifiée\n```\n:::\n\n\n## Test de l'effet d'une ou plusieurs variables\n\nL'ensemble de variables ${\\mathcal V}$ apporte-t-il des informations complémentaires intéressantes sachant que les autres variables sont déjé dans le modèle ?\n\n\\vfill\n\n**Hypothèses** : $H_0$:\"tous les coefficients associés aux variables de ${\\mathcal V}$ sont égaux à 0\" contre $H_1$ : \"au moins un coefficient des variables ${\\mathcal V} \\neq$ 0\n\n**Statistique de test:** $\\displaystyle{F_{obs}=\\frac{SC_{\\mathcal V}/ddl_{\\mathcal V}}{SC_R/ddl_R}=\\frac{CM_{\\mathcal V}}{CM_R} }$\n\n**Loi de la statistique de test:** Sous $H_0$, ${\\mathcal L}(F_{obs}) = {\\mathcal F}_{ddl_R}^{ddl_{\\mathcal V}}$\n\n**Décision** : $\\mathbb{P}({\\mathcal F}_{ddl_{\\mathcal V}}^{ddl_R}>F_{obs}) < 0.05\\ \\ \\Longrightarrow$ Rejet de $H_0$\n\n. . .\n\n::: incremental\n-   Revient à choisir entre le sous-modèle sans les variables ${\\mathcal V}$ ou le modèle complet\n\n-   Si ${\\mathcal V}$ contient tous les effets : revient à tester si $R^2$ est significativement différent de 0, i.e. si toutes les variables sont inutiles (versus au moins une utile)\n\n-   On somme les degrés de liberté associés é l'ensemble ${\\mathcal V}$ sachant qu'1 variable quanti à 1 ddl, 1 variable quali à $I-1$ ddl et une interaction a comme ddl le produit des ddl de chaque facteur\n:::\n\n<!-- \\tiny $\\Longrightarrow$ Pour la séance de TD écrire le test pour 1 variable quali, celui pour 1 interaction, celui pour le test de toutes les variables -->\n\n<!-- * On teste le plus souvent ${\\mathcal V}$ avec 1 variable ou avec toutes les variables -->\n\n## Sélection de variables\n\nSélection de modèle = trouver un compromis entre un modèle qui s'ajuste bien aux données et qui n'a pas \"trop\" de paramètres (Rappel: {{< fa dollar-sign size=1xl >}} {{< fa cake-candles size=1xl >}})\n\n. . .\n\n-   [Enorme littérature sur le sujet](https://scholar.google.fr/scholar?hl=fr&as_sdt=0%2C5&q=model+selection&btnG=){style=\"color:blue;\"}\n\n![](images/model_selection.PNG){width=\"550\" height=\"70\" fig-align=\"center\"}\n\n. . .\n\n-   Souvent utilisé: sélection du modèle qui minimise l'AIC / BIC: compromis entre maximisation de la vraisemblance $L$ (à quel point le modèle s'ajuste bien aux données) et le nb de paramètres\n\n::::: {layout-ncol=\"2\"}\n::: fragment\n$AIC = 2p - 2ln(\\hat{L})$\n:::\n\n::: fragment\n$BIC = pln(n) - 2ln(\\hat{L})$\n:::\n:::::\n\n. . .\n\n{{< fa question size=1xl >}} A votre avis, quelle est la différence entre les 2 critères ({{< bi pencil size=1.5em >}} {{< bi journal-text size=1.5em >}} !)\n\n. . .\n\n::: {style=\"font-size: 85%;\"}\n**Plusieurs stratégies**\n\n-   Construction exhaustive de tous les sous-modèles (long et même impossible si trop de variables)\n-   Méthode descendante (backward): construire le modéle complet; supprimer la variable explicative la moins intéressante et reconstruire le modèle sans cette variable; itérer jusqu'à ce que toutes les variables explicatives soient intéressantes\n-   Méthode ascendante (forward): partir du modéle avec la variable la plus intéressante; ajouter la variable qui, connaissant les autres variables du modèle, apporte le plus d'information complémentaire; itérer jusqu'é ce qu'aucune variable n'apporte d'information intéressante\n-   Méthode stepwise: compromis entre les 2 méthodes ci-dessus\n:::\n\n## Exemple sur ozone: sélection de variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FactoMineR)\nLinearModel(maxO3 ~  ., data = ozone, selection = \"bic\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResults for the complete model:\n==============================\nCall:\nLinearModel(formula = maxO3 ~ ., data = ozone, selection = \"bic\")\n\nResidual standard error: 14.51 on 97 degrees of freedom\nMultiple R-squared:  0.7686 \nF-statistic: 23.01 on 14 and 97 DF,  p-value: 8.744e-25 \nAIC =   613    BIC = 653.8\n\nResults for the model selected by BIC criterion:\n===============================================\nCall:\nLinearModel(formula = maxO3 ~ T12 + Ne9 + Vx9 + maxO3v, data = ozone, \n    selection = \"bic\")\n\nResidual standard error: 14 on 107 degrees of freedom\nMultiple R-squared:  0.7622 \nF-statistic: 85.75 on 4 and 107 DF,  p-value: 1.763e-32 \nAIC =   596    BIC = 609.6\n\nFtest\n               SS  df     MS F value    Pr(>F)\nT12        6650.4   1 6650.4 33.9334 6.073e-08\nNe9        2714.8   1 2714.8 13.8522 0.0003172\nVx9         903.4   1  903.4  4.6094 0.0340547\nmaxO3v     7363.5   1 7363.5 37.5721 1.499e-08\nResiduals 20970.2 107  196.0                  \n\nTtest\n             Estimate Std. Error t value  Pr(>|t|)\n(Intercept) 12.631310  11.000877  1.1482 0.2534427\nT12          2.764090   0.474502  5.8252 6.073e-08\nNe9         -2.515402   0.675845 -3.7219 0.0003172\nVx9          1.292857   0.602180  2.1470 0.0340547\nmaxO3v       0.354832   0.057888  6.1296 1.499e-08\n```\n\n\n:::\n:::\n\n\n## Démarche en modélisation\n\n::: incremental\n1.  Lister les variables potentiellement explicatives / prédictives\n\n2.  Visualiser\n\n3.  Selectionner le sous-modèle (minimisation de l'AIC ou du BIC)\n\n4.  [Interpréter les résultats (quelles variables ressortent ? Est-ce surprenant ? Est-ce en accord avec les connaissances sur le sujet ? Des confusions possibles ?)]{style=\"color:DarkGray;\"}\n\n5.  [Interpréter les coefficients (signe, valeur etc.)]{style=\"color:DarkGray;\"}\n\n6.  [(Prédire pour de nouvelles valeurs)]{style=\"color:DarkGray;\"}\n:::\n\n## Codage et contraintes pour variables quali {.scrollable}\n\n. . .\n\nLa matrice de design $X$ (dans $Y = X\\beta + E$) a autant de lignes que d'individus. Pour les colonnes, c'est variable...\n\n. . .\n\n::: {style=\"font-size: 70%;\"}\n|   | Constante ($\\mu$ ou $\\beta_0$) | Variable quanti | Variable Quali | Interaction quali -quali |\n|----|----|----|----|----|\n| Représentation dans X | Une colonne de 1 | Valeur de la variable | (I-1) colonnes par modalités de chaque variable à I modalités | (I-1)\\*(J-1) colonnes |\n| Degrés de libertés (ddl) | 1 | 1 | I-1 | (I-1)\\*(J-1) |\n| Commentaires |  |  | Contrainte à poser sur les paramètres (le mieux est $\\sum_{i=1}^I \\alpha_i = 0$) | Contrainte à poser sur les paramètres (le mieux est $\\forall i, \\sum_j \\alpha \\beta_{ij} =0$ et $\\forall j, \\sum_i \\alpha \\beta_{ij} =0$) |\n\n: {tbl-colwidths=\"\\[10,15,15,30,30\\]\"}\n:::\n\n. . .\n\n::: callout-important\n## Important\n\n[Le choix de la contrainte impacte FORTEMENT l'interprétation]{style=\"color:red;\"}\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\n1.  $\\sum_i \\alpha_i= 0$, la comparaison est faite par rapport à la moyenne des moyennes par modalité\n2.  $\\alpha_1= 0$, la comparaison est faite par rapport à un niveau de ref (*moins intuitif, et pas pratique quand présence d'interactions*)\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\n*Certaines fonctions de R par défaut utilisent la contrainte 2. !*\n:::\n\n. . .\n\n::: {style=\"font-size: 75%;\"}\nComparez les sorties de ces différentes lignes de code...\n:::\n\n:::::: columns\n::: {.column .incremental width=\"20%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n#lm par défaut\ncoef( lm(maxO3 ~ pluie,\n         data= ozone) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    pluieSec \n   73.39535    27.44523 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column .incremental width=\"35%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n#lm en spécifiant le contraste\ncoef(lm(maxO3 ~ pluie,\n        data = ozone,\n        contrasts = list(pluie= \"contr.sum\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      pluie1 \n   87.11796   -13.72262 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column .incremental width=\"45%\"}\n\n::: {.cell .my_class_code}\n\n```{.r .my_class_code .cell-code}\n# LinearModel prémâche le travaille\nLinearModel(maxO3 ~ pluie,\n            data= ozone)$Ttest\n```\n:::\n\n\n\n::: {.cell .my_class_code}\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error t value Pr(>|t|)\n(Intercept)      87.12       2.42   36.01        0\npluie - Pluie   -13.72       2.42   -5.67        0\npluie - Sec      13.72       2.42    5.67        0\n```\n\n\n:::\n:::\n\n:::\n::::::\n\n## Inteprétation des résultats\n\n-   **Modèle sélectionné** $\\Rightarrow$ Interprétation des résultats\n\n. . .\n\n*2 situations*\n\n1.  Idéale: données équilibrées\n2.  Difficile: données déséquilibrées\n\n. . .\n\nRemarques:\n\n-   Les plans d'expériences permettent d'avoir données équilibrées\n-   En ANOVA, on a souvent des données équilibrées\n\n## Décomposition de la variabilité : variables quali, données équilibrées\n\nQuand les données sont équilibrées, la décomposition de la variabilité est parfaite:\n\n$$\n\\begin{array}{ccl}\n\\displaystyle{\\sum_{i,j,k}(y_{ijk}-y_{\\bullet\\bullet\\bullet})^2}&=& \\displaystyle{\\sum_{i,j,k}\\underbrace{(y_{i\\bullet\\bullet}-y_{\\bullet\\bullet\\bullet})^2}_{\\hat\\alpha_i^2}} + \\displaystyle{\\sum_{i,j,k}\\underbrace{(y_{\\bullet  j \\bullet }-y_{\\bullet \\bullet \\bullet})^2}_{\\hat\\beta_j^2}}\\\\\n&&+ \\displaystyle{\\sum_{i,j,k}\\underbrace{(y_{ij\\bullet }-y_{i\\bullet \\bullet}-y_{\\bullet j\\bullet}+y_{\\bullet \\bullet\\bullet})^2}_{\\widehat{\\alpha\\beta}_{ij}^2}}+ \\displaystyle{\\sum_{i,j,k}\\underbrace{(y_{ijk}-y_{ij\\bullet})^2}_{\\varepsilon_{ijk}^2}}\\\\\n\\end{array}\n$$\n\n. . .\n\nQuand les données sont équilibrées, les coefficients s'estiment simplement:\n\n$$\\begin{array}{c}\n\\hat\\mu=y_{\\bullet \\bullet \\bullet}~~~~~~~~~~~~~~~~~~~~\n\\forall i,~\\hat\\alpha_i=y_{i \\bullet \\bullet}-y_{\\bullet \\bullet \\bullet}\\\\\n\\forall j,~\\hat\\beta_j=y_{\\bullet j \\bullet}-y_{\\bullet \\bullet \\bullet}~~~~~~~~~~~~\n\\forall i,j~\\widehat{\\alpha\\beta}_{ij}=y_{ij \\bullet}-y_{i\\bullet \\bullet}-y_{\\bullet j\\bullet}+y_{\\bullet \\bullet \\bullet}\n\\end{array}$$\n\n. . .\n\n$\\Longrightarrow$ On quantifie parfaitement ce qui est expliqué par chaque variable ou interaction\n\n<!-- ## Décomposition de la variabilité : variables quali, données déséquilibrées -->\n\n<!-- Retour sur un exemple montré plus haut, mais légèrement modifié... -->\n\n\n<!-- \\begin{center} -->\n<!-- \\begin{tabular}{|c|c|c|} -->\n<!-- \\hline -->\n<!-- groupe 1 & groupe 2 & groupe 3 \\\\ -->\n<!-- \\hline -->\n<!-- $y_{11}=6$ & $y_{21}=2$ & $y_{31}=3$ \\\\ -->\n<!-- $y_{12}=9$ & $y_{22}=4$ & $y_{32}=1$ \\\\ -->\n<!-- \\hline -->\n<!-- % Moyennes : $y_{1\\bullet}=7$ & $y_{2\\bullet}=3$ & $y_{3\\bullet}=2$ \\\\ -->\n<!-- \\end{tabular} -->\n<!-- \\end{center} -->\n\n<!-- . . . -->\n\n<!-- Question: comment estimer $y_{2\\bullet}$ ? Deux possibilités ... -->\n\n<!-- . . . -->\n\n<!-- Le déséquilibre induit une une confusion (alias en anglais) -->\n\n<!-- Variables explicatives sont très corrélées $\\longrightarrow$ l’interprétation est très difficile -->\n\n## Comparaison de moyennes ajustées\n\nMoyennes ajustées = $\\hat{\\mu} + \\hat{\\alpha}_i$: Permet de s'affranchir de l'effet des autres variables\n\n. . .\n\nComparaisons possibles 2 à 2, moyennant une correction de Bonferroni par ex.\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\ndata_choco <-read.csv(\"data/chocolat_2022.csv\", sep = \";\")\nmod <- LinearModel(Sucree~Produit+Juge+Produit:Juge, data=data_choco)\nmeansComp(mod,~Produit, adjust=\"bonferonni\")\n```\n\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-73-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$adjMean\n Produit      emmean    SE  df lower.CL upper.CL\n CoteOr_bio70   4.50 0.264 118     3.75     5.25\n CoteOr_bio85   2.42 0.275 118     1.63     3.20\n Equador72      3.88 0.264 118     3.12     4.63\n Lindt70        4.79 0.264 118     4.04     5.55\n Lindt78        4.29 0.264 118     3.54     5.05\n Lindt85        2.58 0.264 118     1.83     3.34\n Repere_bio74   3.88 0.275 118     3.09     4.66\n Repere_bio85   2.46 0.264 118     1.70     3.21\n Villars72      5.54 0.264 118     4.79     6.30\n Villars85      3.17 0.264 118     2.41     3.92\n\nResults are averaged over the levels of: Juge \nConfidence level used: 0.95 \nConf-level adjustment: bonferroni method for 10 estimates \n\n$groupComp\nCoteOr_bio85 Repere_bio85      Lindt85    Villars85    Equador72 Repere_bio74 \n         \"a\"          \"a\"          \"a\"         \"ab\"         \"bc\"         \"bc\" \n     Lindt78 CoteOr_bio70      Lindt70    Villars72 \n        \"bc\"         \"cd\"         \"cd\"          \"d\" \n\nattr(,\"class\")\n[1] \"meansComp\"\n```\n\n\n:::\n:::\n\n\n## Prédictions\n\n$\\hat{Y} = \\hat{\\beta_0} + \\hat{\\beta_1}x_{i1} + \\hat{\\beta_2}x_{i2}  + ... + \\hat{\\beta_p}x_{ip}$\n\nPrédire Y pour : (T12=19, Ne9=8, Vx9=1.2, maxO3v=70) et (T12=23, Ne9=10, Vx9=0.9, maxO3v=95)\n\n. . .\n\nSur PC:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- LinearModel(maxO3 ~  ., data = ozone, selection = \"bic\")\n\nxnew <- data.frame(T12=c(19,23), Ne9=c(8,10), Vx9=c(1.2,0.9), maxO3v=c(70,95))\npredict(model,xnew,interval=\"pred\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr       upr\n1 71.41544 42.90026  99.93063\n2 85.92393 56.76803 115.07983\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(model,xnew,interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 71.41544 64.86327 77.96761\n2 85.92393 76.98627 94.86159\n```\n\n\n:::\n:::\n\n\n## Analyse des résidus\n\n-   Les résidus sont la part du phénomène non-expliquée par le modèle\n\n-   On peut vérifier les hypothèses initiales du modèle\n\n::::: {layout-ncol=\"2\"}\n::: fragment\n\n::: {.cell output-location='fragment'}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-75-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   3  1.5589 0.2036\n      108               \n```\n\n\n:::\n:::\n\n:::\n\n::: fragment\n-   Test de Shapiro-Wilk de normalité des Résidus (Rq : la non-normalité n’est pas un pb tant que la distribution est symétrique)\n\n\n::: {.cell output-location='fragment'}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-76-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  res\nW = 0.97117, p-value = 0.01587\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n## Retour sur l'exemple ozone\n\n::: fragment\n-   Maximum d'ozone : variable réponse\n-   Les variables de températures, nébulosité, vitesse de vent (quanti), et la direction et la pluie (quali) sont prises en compte\n-   On ne sait pas si les interactions entre variables quali et entre les variables quali et quanti sont négligeables $\\Longrightarrow$ on les met dans le modèle\n:::\n\n. . .\n\n`LinearModel(maxO3 ~ (T9 + T12 + T15 + Ne9 + Ne12 + Ne15 + Vx9 + Vx12 + Vx15 + maxO3v + pluie + vent) * (pluie + vent), data=ozone, selection=\"bic\")`\n\nCe qui revient à écrire :\n\n`maxO3 ~ T9 + T12 + T15 + Ne9 + Ne12 + Ne15 + Vx9 + Vx12 + Vx15 + maxO3v + pluie + vent + T9:pluie + T12:pluie + T15:pluie + Ne9:pluie + Ne12:pluie + Ne15:pluie + Vx9:pluie + Vx12:pluie + Vx15:pluie + maxO3v:pluie + vent:pluie + T9:vent + T12:vent + T15:vent + Ne9:vent + Ne12:vent + Ne15:vent + Vx9:vent + Vx12:vent + Vx15:vent + maxO3v:vent`\n\n## Résultat et sortie\n\n\n::: {.cell}\n\n:::\n\n\n`Results for the complete model:`\n\n`Call: LinearModel(formula = maxO3 ~ (T9 + T12 + T15 + Ne9 + Ne12 + Ne15 + Vx9 + Vx12 + Vx15 + maxO3v + pluie + vent) * (pluie + vent), data = ozone, selection = \"bic\")`\n\n`Residual standard error: 14.54 on 56 degrees of freedom` `Multiple R-squared:  0.8658` `F-statistic: 6.569 on 55 and 56 DF,  p-value: 2.585e-11` `AIC =   634    BIC = 786.2`\n\n`Results for the model selected by BIC criterion:`\n\n`Call:` `LinearModel(formula = maxO3 ~ T9 + T15 + Ne12 + Vx9 + maxO3v + vent + T9:vent + T15:vent, data = ozone, selection = \"bic\")`\n\n`Residual standard error: 13.8 on 97 degrees of freedom` `Multiple R-squared:  0.7906` `F-statistic: 26.16 on 14 and 97 DF,  p-value: 8.082e-27` `AIC = 601.8    BIC = 642.6`\n\n## Interprétation des résultats\n\n::::: columns\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               SS df     MS F value Pr(>F)    \nT9          606.2  1  606.2  3.1841 0.0775 .  \nT15         252.8  1  252.8  1.3278 0.2520    \nNe12       2107.0  1 2107.0 11.0664 0.0012 ** \nVx9        1657.3  1 1657.3  8.7046 0.0040 ** \nmaxO3v     5160.8  1 5160.8 27.1060 <2e-16 ***\nvent         12.5  3    4.2  0.0218 0.9956    \nT9:vent    2587.1  3  862.4  4.5294 0.0051 ** \nT15:vent   3722.1  3 1240.7  6.5165 0.0005 ***\nResiduals 18468.3 97  190.4                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\nOn peut dire (à partir des effets significatifs) qu'il y a, sur le max d'O3:\n\n-   des effets de nébulosité de vitesse de vent, du maximum d'O3 de la veille\n-   des effets de la direction du vent et des températures mais à travers les interactions : la direction du vent modifie l'effet de la T$^o$ (i.e. amplifie l'effet de la T$^o$ ou la diminue selon la direction du vent) sur max O3\n:::\n:::::\n\n. . .\n\nOn peut aussi dire (à partir des absences d'effets significatifs):\n\n-   la pluviométrie n'est pas un facteur déterminant qui influe sur le max d'03\n-   une seule nébulosité (Ne12) est conservée dans le modèle : cela ne veut pas dire que les autres nébulosités n'ont pas d'effet (elles peuvent avoir un effet similaire). Idem pour la vitesse de vent.\n-   pour la T$^o$, on a besoin des T$^o$ à 9h et à 15h pour mieux prévoir le maximum d'ozone. L'effet de la T$^o$ n'est pas exactement le même entre 9h et 15h (mais 12h n'est pas utile comme info)\n-   l'effet de la nébulosité est le même quelle que soit la direction du vent. Idem pour la vitesse du vent.\n\n## Interprétation des résultats (2/2)\n\n::::: columns\n::: {.column width=\"65%\"}\n\n::: {.cell}\n<style type=\"text/css\">\n/* size of code output, applied to everything */\n\n.reveal pre {\n  font-size: 1.5rem !important;\n}\n</style>\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate Std. Error t value Pr(>|t|)\n(Intercept)         18.2063    13.7059  1.3284   0.1872\nT9                   1.8269     1.0238  1.7844   0.0775\nT15                  1.0200     0.8852  1.1523   0.2520\nNe12                -3.0132     0.9058 -3.3266   0.0012\nVx9                  2.2213     0.7529  2.9504   0.0040\nmaxO3v               0.3467     0.0666  5.2063   0.0000\nvent - Est           0.4734    17.0102  0.0278   0.9779\nvent - Nord          3.2974    15.0356  0.2193   0.8269\nvent - Ouest        -1.1250    14.0066 -0.0803   0.9361\nvent - Sud          -2.6458    15.1489 -0.1747   0.8617\nvent - Est : T9     -4.7442     2.1418 -2.2151   0.0291\nvent - Nord : T9     6.1408     1.7014  3.6093   0.0005\nvent - Ouest : T9   -0.9505     1.3455 -0.7064   0.4816\nvent - Sud : T9     -0.4460     1.5222 -0.2930   0.7701\nvent - Est : T15     3.6810     1.7967  2.0487   0.0432\nvent - Nord : T15   -5.2279     1.2153 -4.3016   0.0000\nvent - Ouest : T15   0.9797     0.9308  1.0525   0.2952\nvent - Sud : T15     0.5673     1.1111  0.5105   0.6108\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"35%\"}\n-   pour T9 et T15, $\\beta \\ \\neq$ 0\n-   {{< fa plus size=1xl >}} nébulosité, {{< fa minus size=1xl >}} max d'O3 ({{< fa triangle-exclamation size=1xl >}} \\red{signe est le même que celui de la corrélation})\n-   {{< fa plus size=1xl >}} maximum d'O3 de la veille est grand, {{< fa plus size=1xl >}} maximum d'O3 du jour\n-   les jours de vents d'est et surtout du nord ont des max d'O3 supérieur aux jours de vents d'ouest et du sud\n-   les jours de vent du nord, l'effet de la T$^o$ à 9h est plus important (coef $= 6.14$); au contraire quand le vent vient de l'est. C'est l'inverse pour la T$^o$ à 15h\n-   Ainsi, quand le vent du nord, l'effet de la T$^o$ à 9h est particulièrement fort (donc s'il fait chaud à 9h quand le vent vient du nord, le max d'O3 risque d'être important)\n-   etc.\n:::\n:::::\n\n## Démarche en modélisation (bis)\n\n::: incremental\n1.  Lister les variables potentiellement explicatives / prédictives\n\n2.  Visualiser\n\n3.  Selectionner le sous-modèle (minimisation de l'AIC ou du BIC)\n\n4.  Interpréter les résultats (quelles variables ressortent ? Est-ce surprenant ? Est-ce en accord avec les connaissances sur le sujet ? Des confusions possibles ?\n\n5.  Interpréter les coefficients (signe, valeur etc.)\n\n6.  Prédire pour de nouvelles valeurs\n:::\n\n\n\n# Annexes\n\n## Le TCL, c'est PUISSANT {.scrollable}\n\n::: {style=\"font-size: 80%;\"}\n-   Ce que dit le TCL, c'est que peu importe la distribution de base, les moyennes empiriques d'échantillons issues cette distribution auront une distribution normale centrée sur l'espérance de la distribution !\n:::\n\n. . .\n\n::: {style=\"font-size: 80%;\"}\n**Une simulation rapide pour visualiser les choses**\n\n-   Ex distribution $\\chi_2(3)$\n-   On connaît la vraie moyenne de cette loi: 3\n:::\n\n. . .\n\n::: {style=\"font-size: 80%;\"}\nMais dans la *vraie vie*, on aurait accès qu'à un échantillon de cette loi, par ex. de taille $n = 50$. Regardons comment évolue la distribution des moyennes empiriques en fonction de la taille de l'échantillon.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lesson_demarche_stat_files/figure-revealjs/unnamed-chunk-83-1.png){width=960}\n:::\n:::\n\n\n\n\n<!-- Thanks CHAT GPT -->\n\n```{=html}\n<script>\n  document.addEventListener('DOMContentLoaded', function() {\n    // Obtenir toutes les sections avec un H1, en excluant le premier H1 (le titre de la présentation)\n    const h1Elements = Array.from(document.querySelectorAll('h1')).slice(1); // On exclut le premier H1\n    const sectionTitles = h1Elements.map(h1 => h1.textContent);\n    \n    // Créer des éléments de titre pour chaque section (H1 uniquement, sauf le premier)\n    const titleContainer = document.createElement('div');\n    titleContainer.classList.add('title-container');\n    sectionTitles.forEach((title, index) => {\n      const titleElement = document.createElement('span');\n      titleElement.classList.add('section-title');\n      titleElement.textContent = title;\n      titleElement.setAttribute('data-section-index', index);\n      \n      // Rendre chaque titre cliquable pour naviguer vers la section correspondante\n      titleElement.style.cursor = 'pointer'; // Ajouter le style du curseur pour indiquer que c'est cliquable\n    titleElement.addEventListener('click', () => {\n      // Récupérer la diapositive correspondant au H1 sélectionné\n      const targetSlide = h1Elements[index].closest('section');\n      const indices = Reveal.getIndices(targetSlide); // Obtenir les indices de la section (index horizontal et vertical)\n      Reveal.slide(indices.h, indices.v); // Naviguer vers la section correspondante\n    });\n\n    titleContainer.appendChild(titleElement);\n  });\n\n\n  document.body.insertBefore(titleContainer, document.querySelector('.reveal'));\n  function updateSectionTitles() {\n    const currentSlide = Reveal.getCurrentSlide();\n\n    // Vérifier si la diapositive actuelle contient un H1, en excluant le premier\n    let currentSectionIndex = -1;\n    h1Elements.forEach((h1, index) => {\n      if (currentSlide.contains(h1)) {\n        currentSectionIndex = index;\n      }\n    });\n\n    if (currentSectionIndex === -1) {\n      return; // Ne rien faire si aucun H1 n'est trouvé dans la diapositive courante\n    }\n    \n    // Mise à jour du style des titres selon la section courante\n    const titleElements = document.querySelectorAll('.section-title');\n    titleElements.forEach((titleElement, index) => {\n      if (index === currentSectionIndex) {\n        titleElement.style.color = 'black'; // Section active\n        titleElement.style.opacity = 1;\n      } else {\n        titleElement.style.color = 'grey'; // Autres sections\n        titleElement.style.opacity = 0.5;\n      }\n    });\n  }\n  \n  Reveal.on('slidechanged', updateSectionTitles);\n  updateSectionTitles(); // Initialisation au chargement\n  });\n    \n</script>\n```\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}